### ISSUE TITLE
projectionMode and coordinateSystem perform differently for COORDINATE_SYSTEM.IDENTITY

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#1012]
According to the Upgrading from deck.gl v4.1 to v4.2, the old prop projectionMode will be deprecated and replaced with the new coordinateSystem. However, the two props behave differently, at least for the COORDINATE_SYSTEM.IDENTITY.

To reproduce, use the svg-interoperability example, switch the prop in line 118 between projectionMode and coordinateSystem, and check the visual result.

4.1.x using projectionMode: COORDINATE_SYSTEM.IDENTITY
![screen shot 2017-10-10 at 11 02 51 am](https://user-images.githubusercontent.com/144743/31402502-015cc3e2-adab-11e7-8c1f-791597669bf9.png)
^ Expected result.

4.1.x using coordinateSystem: COORDINATE_SYSTEM.IDENTITY
<img width="886" alt="screen shot 2017-10-10 at 11 03 10 am" src="https://user-images.githubusercontent.com/144743/31402440-d3249824-adaa-11e7-8e1c-21915728e584.png">
(Not only there's an offset, but also the projection is off - polar being distorted)

4.2.x using either projectionMode/coordinateSystem: COORDINATE_SYSTEM.IDENTITY
<img width="546" alt="screen shot 2017-10-10 at 11 03 47 am" src="https://user-images.githubusercontent.com/144743/31402442-d4bf0bce-adaa-11e7-9457-bd5498aede55.png">

Users using v4.1.x with the old API projectionMode should be not affected, but it is breaking for v4.2.x.

**Comment by jianhuang01** [comment]
@gnavvy Would you please paste the code change for line 118? I don't know how to switch between projectionMode and coordinateSystem. Thanks!

**Comment by ibgreen** [comment]
@gnavvy Thanks for bringing this up, this should be sorted asap.

The motivation for this change is that for geospatial projections, the "overlaid" meter coordinate system's positive y axis should point to north, and I found that it was possible to unify some of the geospatial matrix creation logic by 

This is my current assessment:
* For `COORDINATE_SYSTEM.IDENTITY`, we should clearly not be flipping Y coordinates. Identity means identity.
* For `COORDINATE_SYSTEM.METER_OFFSETS` backwards compatibility we should check if the layer is using `projectionMode` instead of `coordinateSystem` and in that case disable the flip. 

Both code and documentation and perhaps a test case should be added.

**Comment by gnavvy** [comment]
Found the issue: there are extra direction calculations based on _pitch_ and _bearing_ in the _FirstPersonView_ class, and having _OrthographicViewport_ extends the _FirstPersonView_ seems led to the problem. Having _OrthographicViewport_ extends Viewport directly solves the issue.

Personally, I am still skeptical about having _OrthographicViewport_ and _PerspectiveViewport_ extends the _FirstPersonViewport_. _OrthographicViewport_ and _PerspectiveViewport_ and commonly used in CG in general and I don't think our users will expect hidden _pitch_ and _bearing_ based operations in the hidden parent class, which are map-specific.

Shall we resume _OrthographicViewport_ and _PerspectiveViewport_ from depreciation? @ibgreen 

Also, https://github.com/uber/deck.gl/blob/master/src/core/viewports/first-person-viewport.js#L40
should up = [0, 1, 0] instead of [0, 0, 1]? or is it desired?

**Comment by shaojingli** [comment]
this up vector stuff has confused @Pessimistress as well when she is fixing the surface normal calculation for the polygon layer here https://github.com/uber/deck.gl/pull/1011

**Comment by ibgreen** [comment]
> Shall we resume OrthographicViewport and PerspectiveViewport from depreciation? @ibgreen

I mainly want to make sure we don't create a complicated controller hierarchy just because we have a bug or haven't thought through the issues enough.

A few observations:


* The target end state for the Controller and Viewport system is that all Viewports and Controllers work against a common `ViewState` that contains a position and a direction.




* `OrthographicViewport`s are created by creating a `Viewport` and giving it a `projectionMatrix` argument set to an orthographic projectionMatrix.

The main reason I can see for creating pure OrthographicViewports and PerspectiveViewports would be to completely opt out of the controller system, and I suspect that is not what you want.

**Comment by ibgreen** [comment]
> Shall we resume OrthographicViewport and PerspectiveViewport from depreciation? @ibgreen

Updated answer

I mainly want to make sure we don't create a complicated controller hierarchy just because we have a bug or haven't thought through the issues enough.

Q1: Do you want to calculate your own view matrix or do you want it to be calculated from the view state? If the latter let'd drill down to the details of how you want it calculated. I think it is the OrbitController that may need a bit of work to generate the right direction for the new Viewport system

Q2: Let's think about the up vector.
* In geospatial coordinate modes, it seems natural that Z is up. In a geospatial first person view, that must be the desired default?
* In other modes, one needs to define what is up. GL convention is that positive Z goes into the screen, so that Y is up and X,Y corresponds to the "screen".
Should we define the default differently depending on whether a geospatial anchor is provided?


A few observations:

* By default, the basic `Viewport` class is effectively the `PerspectiveViewport` (i.e. it sets the projection matrix to a perspective projection matrix) unless one explicitly gives it a different projection matrix.  Which means that `PerspectiveViewport` is already supported, so keeping one more class for it didn't seem to make sense.

* The target end state for the Controller and Viewport system is that all Viewports and Controllers work against a common `ViewState` that contains a position and a direction. The main reason I can see for creating pure OrthographicViewports and PerspectiveViewports would be to completely opt out of the controller system, and I suspect that is not what you want.

**Comment by gnavvy** [comment]
A1: 
> Q1: Do you want to calculate your own view matrix or do you want it to be calculated from the view state?

It is preferable to have the controller generate the view matrix, we've agreed on this.

Currently, there are several sets of view/controls we have WIP:
  - map-related: map-control, map-state, web-mercator-viewport. check √
  - general 2D/3D: according to the [RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.0/first-person-mercator-viewport-rfc.md), the third-person-* goes here. 
For 3D: orbit-control(viewport-control?), orbit-state, orbit-viewport (perspective-viewport). 
For 2D: we don't have any other than the orthographic-viewport.

So it seems the perspective-viewport/orbit-viewport and the orthographic-viewport should extend the third-person-viewport instead of the first-person-viewport. Having pitch and bearing in the first-person-viewport also makes users (at least me) think it is designed for map use cases.

A2:
> In geospatial coordinate modes, it seems natural that Z is up. In a geospatial first person view, that must be the desired default?

Agree, it is the comment _"default positive y axis"_ in [that line](https://github.com/uber/deck.gl/blob/master/src/core/viewports/first-person-viewport.js#L40) that tricked me. In the first-person view case, up should be [0, 0, 1]. We are on the same page.

> By default, the basic Viewport class is effectively the `PerspectiveViewport` (i.e. it sets the projection matrix to a perspective projection matrix) unless one explicitly gives it a different projection matrix. Which means that PerspectiveViewport is already supported, so keeping one more class for it didn't seem to make sense.

The base Viewport class does not have interfaces like `eye`, `lookAt`, `up`. The orbit-control can bypass the generation of these vectors for the `PerspectiveViewport` but we are assuming the users will always use a controller. (Often I only want a static viewport but I'm okay to wrap my Deck.gl instance w/ a controller in this case.) Also, we don't have a 2D controller yet to generate the eye, lookAt, up vectors for the `OrthographicViewport` yet that I'll have to keep the `OrthographicViewport` before we add a 2D controller.

**Comment by 1chandu** [comment]
Need to be verified.

**Comment by jianhuang01** [comment]
https://github.com/uber/deck.gl/pull/1125
Fixed here.
