### ISSUE TITLE
ScatterplotLayer radius changes when panning

### ISSUE THREAD

**Issue by Scoreaux** [uber/deck.gl#1080]
When using a ScatterplotLayer inside a ReactMapGL wrapped DeckGL component, the circle radius is affected by panning towards the top or bottom of the map (but the center point of the circle remains correct).

I have checked that DeckGL is receiving the same viewport object as ReactMapGL when interacting with the map. I couldn't see anything in the documentation that would explain this behaviour, any ideas?

deck.gl - v4.1.5
react-map-gl - v3.1.1

```
<ReactMapGL
        onViewportChange={updateViewport}
        {...viewport}
      >
        <DeckGL
          {...viewport}
          layers={[
            new ScatterplotLayer({
              id: 'circle-layer-test',
              data: [[0, 0]],
              getPosition: e => e,
              getRadius: () => 900000,
              getColor: () => [0,0,255,255],
            }),
          ]}
        />
      </ReactMapGL>
```

Radius is smallest when centered:
<img width="644" alt="screen shot 2017-10-26 at 15 04 57" src="https://user-images.githubusercontent.com/11053684/32058010-c84c8b56-ba60-11e7-8f0b-809d80f87eea.png">
Radius grows when panning towards top or bottom of map:
<img width="651" alt="screen shot 2017-10-26 at 15 04 49" src="https://user-images.githubusercontent.com/11053684/32058016-c9a5d4a8-ba60-11e7-9881-d877ffa4cdf4.png">

**Comment by ibgreen** [comment]
@Scoreaux Fascinating! It looks like you have created a live demonstration of [Tissot's indicatrix](https://en.wikipedia.org/wiki/Tissot%27s_indicatrix) for the web mercator projection. The tl;dr is that the indicatrix shows how various cartographic projections distorts distances across the globe.

What is happening is that deck.gl interprets the size you provide in meters by rendering it according to the local "web mercator distance scale" which depends on your viewport center's distance from the equator. The effect is normally not noticeable when zoomed in, but when visualizing the entire world like this, it is.

In this case you likely just want to specify your radius in pixel units rather than in meters. The `ScatterplotLayer` has `minRadiusPixels` and `maxRadiusPixels` props to help with this.

**Comment by Scoreaux** [comment]
Hi @ibgreen, thanks for the prompt response! That was a fascinating read, I should've expected it to be something like that causing this.

What I'm trying to do is display ~200 circles on a map with varying sizes based on the data they're displaying. I looked at using min/MaxRadiusPixels for this, however, because I can't specify the values for these keys as a function (like I can with getRadius, getColor etc.), it means I either have to choose between having the circles all the same size by setting min and maxPixelRadius to the same values, or allow the circle sizes to vary based on map position. Is that correct?

Can you see any other way of accomplishing this?

**Comment by ibgreen** [comment]
@Scoreaux if you have multiple points that you want to be individually specified in pixels at the world zoom level, it might be necessary to do a custom `ScatterplotLayer` and change one line in the vertex shader.

You'd copy the vertex shader file and wire it up like this:
```
import CUSTOM_VERTEX_SHADER from './..';

class PixelScatterplotLayer extends ScatterplotLayer {
   getShaders() {
      return Object.assign({}, super.getShaders, {vs: CUSTOM_VERTEX_SHADER})
   }
}
```
