### ISSUE TITLE
Avoid importing package.json into bundle

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#1088]
To get access to the current version, deck.gl imports `package.json`.

* Since our package.json has grown big, this adds a couple of unnecessary kilobytes to the bundle
* Can also cause issues for users that redefine json loaders, see #1087 

The best solution is probably to write our own small webpack plugin to generate a minimal version file from the info in package.json.

**Comment by Apercu** [comment]
Because we already have the global version defined [here](https://github.com/uber/deck.gl/blob/e93b524858ac6e230305b78afd489bab758f3984/webpack.config.js#L51), we should be able to use this instead of importing the package in `core/lib/init`

Another point, I think `VERSION` is too generic it might conflict with user code / libs, we should change it to `DECK_VERSION` or similar

**Comment by ibgreen** [comment]
Agreed. And we can do the same change in luma.gl, should give us some bundle size savings, every bit helps.
