### ISSUE TITLE
How to change the trips linewidth. the strokeWidth  didn't work.

### ISSUE THREAD

**Issue by Wwangchen** [uber/deck.gl#1117]
Has there been an update and is there a simple method to adjust strokeWidth - if so, how ?

**Comment by ibgreen** [comment]
@Wwangchen as you seem to be aware this is a known issue, see #725.

It is on our radar but no update yet, unfortunately.

**Comment by Wwangchen** [comment]
@ibgreen Thank you very much.And how could I do ,if I want to change the tripsLayer width.  I don't  
know where  to code .

**Comment by thuanmb** [comment]
@Wwangchen I'm facing the same issue. I think you can start from here: https://github.com/uber/deck.gl/pull/352/files.
Basically, we will need to update the model to use `TRIANGLE_STRIP` and update `trips-layer-vertex.glsl.js` to have something similar like this.
https://github.com/uber/deck.gl/blob/9441791f0f5ca8c33cb947eef0458d63e67f724e/src/layers/core/line-layer/line-layer-vertex.glsl

But with the `TRIANGLE_STRIP`, we need to know the start and end points of a line. And I'm not sure how can we do it with the path data. May be split it into lines instead of return whole path from `getPath` method.
