### ISSUE TITLE
Don't understand how to render point cloud data(laz format)

### ISSUE THREAD

**Issue by algaes1** [uber/deck.gl#1121]
I went through the point-cloud-laz example, it was rendering and rotating the object 360. I am working on lidar data, i need to iterate point one at a time instead of rendering all at a time. Let me know is there any api supplied by deckgl, if not please help on this how to do this.

**Comment by ibgreen** [comment]
@algaes1 Can you be more specific?  What does "iterate one point" at a time mean? 
* Do you need to do some post-processing on the data before you display it?
* Or do you actually want to draw one point at a time?

**Comment by algaes1** [comment]
Currently it extract the point cloud data, render and rotate all point at a time. Now to show motion what exactly happened during lidar data capture it need to draw one point at a time. I want to show motion what happened during data capture.

**Comment by ibgreen** [comment]
@algaes1 Understood. You have a time stamp on each point. I suspect that rather than draw one point at a time, you want to draw only the points that were captured at a specific time (or time interval), and gradually change that time as a uniform, animating the cloud.

We don't support time based filtering of points yet, but this is not too hard to add to the point cloud shader yourself, depending on your comfort level with such things.

**Comment by algaes1** [comment]
@ibgreen Thanks. I am new to this. Can you suggest some documentation / references / code to achieve  this?

**Comment by ibgreen** [comment]
> Can you suggest some documentation / references / code to achieve this?

@algaes1  I'd probably start with reading the [deck.gl documentation](http://uber.github.io/deck.gl/#/documentation/custom-layers/writing-your-own-layer)
