### ISSUE TITLE
Conditional Visibility - Setting Layer Visibility by Props and State

### ISSUE THREAD

**Issue by winston-bosan** [uber/deck.gl#1221]
## What is the ideal implementation for real time display/off-display of a layer? 
Hello people! After reading the documentation of deck.gl I decided to work on a simple project, and all was going well.
However, since the documentation mentioned layer visibility is best controlled by the visible property (instead of rerendering everytime a function return), I decided to attempt it. 
I tried to use redux, parent props, state, function and many other solutions. In the end, I was unsuccessful.  

```
    new PolygonLayer({
            pickable: true,
            onClick: info => {
                //Update Global Redux Store
                this.props.setActiveUnit(info.object.properties.AREA_NAME);
                this.props.setActiveLayer("neighborhood");
                var newCenter = centroid(info.object.original).geometry
                    .coordinates;
                this.props.goTo({
                    longitude: newCenter[0],
                    latitude: newCenter[1],
                    zoom: 11.5
                });
                this.setState({ showDistrict: false }); //Trying to setState show District
                this.districtData = [{ trying: "hi" }]; //Slowly growing desperate, I tried to force the object to refresh all atributes
            },
            onHover: info => this.onUnitHover(info),
            autoHighlight: true,
            id: "district-layer",
            data: this.districtData,
            visible: this.state.showDistrict, //1st, I thought primitives are not actively managed by PolygonLayer
            filled: true,
            stroked: true,
            extruded: false,
            lineWidthMinPixels: 2,
            getLineColor: d => this.state.storkeColor,
            updateTriggers: {
                //Update Triggers doesn't include visible I suppose
                visible: [this.state.showDistrict]
            }
        })

```

**Comment by ibgreen** [comment]
> (instead of rerendering everytime a function return),

@winston-bosan . I probably didn't understand your comment, but at least I can confirm that you do need to re-render the layer every time a prop changes. If you don't tell deck.gl what has changed, how could it know how/when to rerender?

About visibility, it is a perf tradeoff. If you don't include the layer in the layer list in the next render, all state will be destroyed. If you then include it again, all state will be rebuilt. This is an expensive operation. Because of this it is often good to keep rendering your now invisible layer, with `visibililty` prop set to false, rather than to stop rendering that layer.

**Comment by winston-bosan** [comment]
@ibgreen Tis my folly! Of course rerendering is demanded to draw the new layer. I was just a bit confused about the visibility wording on the documentation then. Good cheers!
