### ISSUE TITLE
Can't get GeoJSON layer to render in front of GridLayer

### ISSUE THREAD

**Issue by Warkst** [uber/deck.gl#1361]
I'm not sure if I'm doing something wrong, but I can't get my `GeoJsonLayer` to render on top of my `GridLayer`. I'm storing the layers of my `DeckGL` element in the state and add layers dynamically. If I add a `GridLayer`, I can't seem to get a `GeoJsonLayer` to appear on top of it. I update the layers array by calling `setState` (the react way) and I've tried adding the `GeoJsonLayer` at the back and at the front of the array, with no luck.

What should I do to show the `GeoJsonLayer` on top of the `GridLayer`?

I've added a minimal, runnable react project showing this behavior. Should be as simple as unzip, `npm install` and `npm start`. Click the buttons at the top to add the layers. The buttons at the top do pretty much what they imply: "Add grid" adds the `GridLayer` (to the back of the layers array), "Add GeoJSON back" adds the `GeoJsonLayer` to the back of the layers array and "Add GeoJSON front" adds it to the front. You must refresh the page to start anew.

[minimal.zip](https://github.com/uber/deck.gl/files/1673701/minimal.zip)

**Comment by ibgreen** [comment]
@wrkst OK, let's see if I can explain this...

in deck.gl v5 we made a change to enable WebGL `depthTesting` by default. 
* We did this, because `depthTest: true` is needed for drawing 3D/extruded layers.
* But this can cause issues when drawing multiple "2D" or "flat" layers at the same depth won't be drawn, since something has already been drawn at that "depth".
* For a quick fix use `onWebGLInitialized` callback to disable depth testing. See code below

Other tips:
* You could e.g. set `opacity: 0.2` on your grid layer, simplifies debugging.
* I don't think your frontGeojson ends up last in the list if that is what you wanted. the way you coded it, I believe that gridlayer often ends up last of the three.

Finally, deck.gl is designed to efficiently allow you to rerender layers every "frame", just like you are rerending your React components every frame. Caching the layers in state really complicates your otherwise very clean app for what we believe is almost zero perf gain. Look at any of our examples to see how we do it.

```
import {setParameters} from 'luma.gl';

....
                   <DeckGL {...this.state.viewport}
                      onWebGLInitialized={this.onWebGLInitialized}
                      layers={this.state.layers}/>
                </ReactMapGL>
            </div>
        );
    }

    onWebGLInitialized(gl) {
      setParameters(gl, {depthTest: false});
    }
```

**Comment by Warkst** [comment]
@ibgreen thanks for answering. I think I understand and will try this tomorrow and post an update here, but I expect things will work from your explanation.

To be honest with you, I'm really new to react and web development in general. This my first react app and I patched things together from reading some react 101 and reverse engineering some examples. I was surprised everything worked, but I guess it's no real surprise to hear i did things wrong. I will take another look at some of the examples at how to add/remove layers dynamically without binding the layers property to the component's state. I'm really enthusiastic about this project though, thanks for all the work you guys put into deck gl, it's pretty damn amazing!

**Comment by Warkst** [comment]
@ibgreen as expected, the quick fix works like a charm.

I've been thinking about the other thing you said, regarding rerendering the layers each 'frame'. If I understand correctly it would make more sense to have a function like `renderLayers` and then replace `{this.state.layers}` by `{this.renderLayers()}`. This function should create an array of layers and return it. For that to work I suppose I need to replace `state.layers` by the properties needed to initialize the layers? Thanks again!
