### ISSUE TITLE
moving choropleth out of view causes errors (3.x)

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#137]
Release: 3.0.0-beta28

If you zoom in until a choropleth is out of view, the console spews hundreds of these warnings:

```
[.Offscreen-For-WebGL-0x7fe9da94a800]GL ERROR :GL_INVALID_VALUE : LineWidth: width out of range
[.Offscreen-For-WebGL-0x7fe9da94a800]GL ERROR :GL_INVALID_VALUE : LineWidth: width out of range
[.Offscreen-For-WebGL-0x7fe9da94a800]GL ERROR :GL_INVALID_VALUE : LineWidth: width out of range
```

Using lineWidth of 1

**Comment by ibgreen** [comment]
@contra Can't seem to be able to repro this.

Can you put a breakpoint in Choropleth layer `draw` method and see what lineWidth it is using?

We added support to scale the lineWidth with the devicePixelRatio to make it look more consistent between retina and non-retina, so the problem is probably related to that.

**Comment by contra** [comment]
@ibgreen Width is 2. Renders just fine. Using the 64 bit layer, btw.

**Comment by ibgreen** [comment]
Fixed in latest betas.
