### ISSUE TITLE
can't add and remove layer 

### ISSUE THREAD

**Issue by heshan0131** [uber/deck.gl#14]
run into error:
[object] has other than one matching layers

**Comment by ibgreen** [comment]
@wwwtyro this is becoming a critical issue for Shan's app. 

The issue is related to the layer needing to register a new Program etc, it always seemed hard to fix in PhiloGL since it uses a declarative approach for setting up programs making it a little tricky to figure out how to add and remove them after initialization.

This should be much more straightforward to fix using luma.gl once the ongoing port is complete.

@heshan0131 We might want to extend the example code to add and removes layers in a way that reproduces the issue.

**Comment by wwwtyro** [comment]
:+1: It'd be great if I can get a reproducible example.

**Comment by heshan0131** [comment]
@wwwtyro I will edit the example code, and do a pull request?

**Comment by wwwtyro** [comment]
That'll work, or you can just make a branch and push it and tell me where it's at so I can try it. :)

**Comment by heshan0131** [comment]
yes will do

**Comment by heshan0131** [comment]
@wwwtyro 
example added in
https://github.com/heshan0131/deck.gl/tree/dynamic-layer-example

**Comment by wwwtyro** [comment]
Thanks! I'll make sure it works when I get luma.gl working with deck.gl. :)

**Comment by ibgreen** [comment]
@heshan0131 Please retest this on the performance branch. Layer handling has been rewritten so if it is still an issue let us fix it in the right place.
