### ISSUE TITLE
examples/experimental/js/with-mapbox-map not working OOB

### ISSUE THREAD

**Issue by alandroid** [uber/deck.gl#1502]
**examples/experimental/js/with-mapbox-map** not working 'out of box':

#### Actual Result
Deck.GL layer did not render, mouse navigation not working.

```
Uncaught TypeError: Deck is not a constructor
    at App.onLoad (app.js:84)

app.js:58 Uncaught TypeError: Cannot read property 'setProps' of undefined
    at App.setProps (app.js:58)
    at App.onResize (app.js:66)
```

#### Expected Result
Deck.GL layer renders ontop of MapGL and mouse navigation works.

#### Reproduce Steps
git clone https://github.com/uber/deck.gl.git
cd examples/experimental/js/with-mapbox-map
npm install
npm start

Should i just wait till the JS API is official? 
https://github.com/uber/deck.gl/issues/1429

**Comment by ibgreen** [comment]
@alandroid Yes looks broken, thanks for reporting! While we make efforts to keep everything working, the master branch is essentially always under development so it can break, especially in the experimental stuff which we are actively working on.

For that reason it is recommended to use a release branch when working with examples. I just tried the same example on the `5.1-release` branch and it worked. `

Also, `npm run start-local` will build against local deck.gl source (as opposed to `npm start` which used the installed deck.gl lib) so that is also worth trying, especially if you run on master.

There is a [section in the docs](http://uber.github.io/deck.gl/#/documentation/getting-started/installation?section=running-the-examples) that attempts to explain this.
