### ISSUE TITLE
Possible Memory Leak with GeoJsonLayer

### ISSUE THREAD

**Issue by dvad924** [uber/deck.gl#1508]
### Use Case 
Pulling geojson features out of mapbox vector tiles and put them into deck.gl's 
    GeojsonLayer because it styles faster and smoother than data-driven-styles

#### Actual Result
Geojsonlayer correctly renders whatever Geojson object is passed to it
    but previous Geojson objects are ineligible for garbage collection due to
    back references from a layer's oldProps.
    This is not an issue if the Geojson object is the same as the previous one
    but completely new Geojson Objects result in leaks. 
    Memory footprint of page quickly goes over 1GB
```
backDepth = (x,c) => {if(!x) return c; else return backDepth(x.oldProps._layer,c+1);}
backDepth(props._layer,0) //// 8924
```
where ```props._layer.oldProps.data === props.data ///false```
 
#### Expected Result
Geojsonlayer would render whatever current Geojson object is passed to it correctly on
    the given map and previous Geojson objects that were passed as data props
    would be eligible for garbage collection.
#### Reproduce Steps
I have gotten this result consistently with the following example
     https://gist.github.com/dvad924/8e64868487f5115bf7a67252716f571b
     I used setInterval to automate the problem but if it is 
     too heavy to run remove that line.
     You can simulate the issue by dragging/zooming in the map
Chrome Version 64.0.3282.186 (Official Build) (64-bit)

#### Possible Reason
This isn't temporary
https://github.com/uber/deck.gl/blob/a642c17bc579ec375f6efa63246c85589b981ffa/src/core/lib/layer.js#L685

**Comment by ibgreen** [comment]
@dvad924 - Thanks for the detailed report, it will take a little while to dig into all the details. 

I see two possible problems:
* A possible bug: We do intentionally keep the most recent previous set of props around. Any older props should be released, and if that isn't happening we should address that. If your timer keeps growing the heap then that would be an indication.
* A possible optimization: As you say, it would be desirable to release `data` even from the most recent previous props since `data` can be very big. I agree. This will require careful analysis of our layer lifecycle to make sure all current and planned layer code will still work, but I agree that we should open a task for this.

**Comment by jianhuang01** [comment]
duplicate with #1548
