### ISSUE TITLE
layer-browser broken on master

### ISSUE THREAD

**Issue by chrisgervang** [uber/deck.gl#1581]
#### Actual Result
<img width="1066" alt="screen shot 2018-03-25 at 9 19 22 pm" src="https://user-images.githubusercontent.com/2461547/37886784-41c54770-3072-11e8-81f8-3f746df947be.png">
<img width="534" alt="screen shot 2018-03-25 at 9 19 12 pm" src="https://user-images.githubusercontent.com/2461547/37886785-41db49a8-3072-11e8-95be-81dbd227ebb9.png">

#### Expected Result
Map to render and path layer & scatter plot layer renders
#### Reproduce Steps
on master, in layer-browser example, npm install, then npm run start-local

**Comment by 1chandu** [comment]
@Pessimistress @ibgreen 
This is triggered by #1561 
We are caching `Program` objects, but when `Model.delete()` is called , it is triggering `Program.delete()`, that deletes WebGL handle, but re-creation of the `Model` by the same layer (with same shaders) gives the deleted program object. Program objects are being cached to save `linkProgram` time. Couple of options.
1. For now disable Program object caching (set _cachePrograms to false when creating shaderCache, I verified it), and then work on a solution so that only a limited number of Program objects are cached (LRU or something else).
2. If 'Program' deletion is not needed for #1560, we can remove 'program.delete()' form Model.delete(), so cached program objects will be eventually garbage collected.

**Comment by 1chandu** [comment]
This issue is fixed in luma.gl https://github.com/uber/luma.gl/pull/467 and a new alpha version of luma.gl `5.2.0-alpha.8` is published. I am working on updating deck.gl repo with this new version.

**Comment by Pessimistress** [comment]
@1chandu https://github.com/uber/deck.gl/issues/1560 was published as a 5.1 patch, we need to do the same for the luma.gl fix.

**Comment by 1chandu** [comment]
Resolved with #467, also published new alpha release and patch release.
