### ISSUE TITLE
TextLayer does not render well on Windows/Chrome

### ISSUE THREAD

**Issue by georgios-uber** [uber/deck.gl#1608]
Windows with Chrome 65. Nvidia Quadro M2000.

#### Actual Result
<img width="94" alt="screen shot 2018-03-30 at 4 00 55 pm" src="https://user-images.githubusercontent.com/25012840/38156565-cb03f5ee-3433-11e8-80d3-940fe9426811.png">

#### Expected Result
Proper rendering.

#### Reproduce Steps
1) Run layer browser
2) View TextLayer

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by jianhuang01** [comment]
@georgios-uber After investigation the root cause is from chrome's inconsistent text alignment on windows and osx for some font faces, microsoft edge couldn't guarantee the correctness for each font face either. One possible solution in short term is that we can expose an API to specify a font face which you can choose to make sure it works for chrome 65. How do you think?

**Comment by georgios-uber** [comment]
This issue still reproduces on 5.3.0-alpha.1
