### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by caffeine-potent** [uber/deck.gl#1673]
#### Background  
I have geo-referenced rasters that would be interesting to visualize. 

I'd like to start using or contributing to deck. However, I'm not very knowledge-able about the direction it's taking.  Is there a long term list of features we'd like to see in Deck.GL? Are there any ideas/intentions to take it further?

**Comment by ibgreen** [comment]
@caffeine-potent Great news, we'd love to have you as a contributor! In fact, one of our goals for deck.gl is to develop an "open governance model" that makes it easy for external contributors to engage. So far we have put up a [roadmap page](http://uber.github.io/deck.gl/#/documentation/overview/roadmap) (since a new release is imminent, it might be best to read the version on [master](https://github.com/uber/deck.gl/blob/master/docs/roadmap.md)) as a first step.

In addition, the dev-docs folder contains a growing body of "meta information" about the project. In particular you are going to want to go through the RFC folders where we lay out technical details of new features, welcoming public discussion.

Take a look and let us know how things look from your end, i.e. let us know what you would like to see to make it possible for you to engage in an efficient way.
