### ISSUE TITLE
Timestamp in Trips Layer trips.json segments 

### ISSUE THREAD

**Issue by patil-ashwini** [uber/deck.gl#1854]
What is the timestamp format in segments in trips.json in https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/trips/trips.json?
[longitude, latitude, time]

**Comment by JamesSingleton** [comment]
I have the same questions... Because the timestamps given `1193.803` if you put them in any timestamp converter give you like a 1969 date. However, the demo says that the trips are from 2016... My issue is that is I put an actual timestamp in like 1467485784 it breaks the trips layer / it doesn't render.

**Comment by JamesSingleton** [comment]
@ibgreen so if I just kept this.state.time to the timeStamp, I _should_ be fine. However, I think my problem is mainly #2186. I got it to _work_ but the performance is terrible with large datasets.

**Comment by ibgreen** [comment]
Tracked in #2523 (Trip Layer)
