### ISSUE TITLE
Creating custom layer

### ISSUE THREAD

**Issue by kutuev** [uber/deck.gl#1960]
Hello,

I need to create a custom layer (arrow, sphere primitives), but there is no example how to do it.
I investigated LumaGL documentation, but there is no real examples, Luma contains a lot of examples but without shaders in this case it's quite difficult to have a starting point.

Do we have something like this? 

What is more, can I debug shader code?

**Comment by ibgreen** [comment]
> but there is no real examples,

The best examples would likely be source code of the existing layers. Start by looking at a simple layer like scatterplot layer and try to make some modifications to the shaders, change color in the fragment shader, rerun, one change at a time.

A good way to test layers may be to use and modify deck.gl's [layer browser](https://github.com/uber/deck.gl/tree/5.3-release/examples/layer-browser) example. (Remember to run it from a release branch rather than master)

> I need to create a custom layer (arrow) 

For arrows, check out the `PathMarkerLayer` in @deck.gl/experimental-layers. It uses the experimental `MeshLayer` with a small arrow geometry. You can play with it using the layer browser. Maybe it can serve as inspiration.

> What is more, can I debug shader code?

While you can't put breakpoints in the shader itself, luma.gl has debug support to write all shader input data to the console, which can often be quite helpful as a lot of issues stem from some uniform or attribute containing the wrong data. A starting point is here [in the docs](http://uber.github.io/deck.gl/#/documentation/developer-guide/debugging?section=webgl-debugging-using-luma-gl).
