### ISSUE TITLE
Pan/Zoom for orthographic view?

### ISSUE THREAD

**Issue by mangkang** [uber/deck.gl#2095]
Hi,

I am working on a prototype to render 2d graphs with pre-generated layout using OrthographicView (with PathLayer and IconLayer) sort of similar to the graph example. 

I am new to deck/webgl and would appreciate any tips/examples/input with regard to implementing pan/zoom using this view.

Thanks.

**Comment by Pessimistress** [comment]
@gnavvy @javidhsueh Is there a orthographic controller implemented for graph.gl?

**Comment by javidhsueh** [comment]
Yes. I do have the implementation for zoom/pan/center the viewport in graph.gl.
Should we want to move that piece of code into Deck.gl? Or should we leave it in Graph.gl until it's mature? 
@ibgreen

**Comment by ibgreen** [comment]
@javidhsueh Yes we need such a controller in deck.gl, so I'd be open to having this added as an experimental class, and then we audit and refine it so that we can make it official.

Ideally this new controller should be based on the existing controller architecture (a subclass of `Controller`). 

However, the current controllers in graph.gl are react components. Let's first discuss to understand how much work it would be to convert these to the new `Controller` model.

**Comment by tgorkin** [comment]
@javidhsueh The orthographic controller seems to be on track fro 7.0 but no documentation exists?
