### ISSUE TITLE
Improve custom layer compatibility

### ISSUE THREAD

**Issue by sakitam-fdd** [uber/deck.gl#2296]
#### Background 

For #2264 mapbox custom layer integration, it introduces an external GL context for mapbox. It's exciting, but for other map engines like [maptalks](https://github.com/maptalks/maptalks.js) canvas in the GL context created externally is not rendered correctly，and I've found some reasons：

- Externally created temporary canvas does not update `clientWidth` and `clientHeight`, so I modified the following two places.
https://github.com/uber/deck.gl/blob/4779b1040c6379c713f1a8b2d6b688b2b2909982/modules/core/src/lib/deck.js#L358
https://github.com/uber/deck.gl/blob/4779b1040c6379c713f1a8b2d6b688b2b2909982/modules/core/src/lib/draw-layers.js#L40

  clientWidth => width
  clientHeight => height

- This is the examples [maptalks.deckgl](https://github.com/sakitam-gis/maptalks.deckgl)

![animation2](https://user-images.githubusercontent.com/19517451/45821239-45f12b80-bd1b-11e8-82d6-b0aefca0575c.gif)

- So I think the above modifications will have better compatibility.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
> So I think the above modifications will have better compatibility.

@sakitam-fdd Thanks for reporting! We are of course interested in improving compatibility with other systems, however using `clientWidth` and `clientHeight` is critical in order to correctly support retina displays. 

https://webglfundamentals.org/webgl/lessons/webgl-anti-patterns.html.

`clientWidth` represents the size of the canvas on screen, and in retina mode it will be smaller than the `width` and `height` which represent the actual size of the underlying WebGL drawing buffer, which will be scaled to the `canvasWidth`.

We could use `width` if `clientWidth` is not defined. But per your description, it sounds like clientWidth is defined but not updates. I am not sure how to detect that your underlying module does not update `clientWidth`.

**Comment by sakitam-fdd** [comment]
Thank you for your reply, I will think about other solutions, or you have better suggestions:grinning:

**Comment by sakitam-fdd** [comment]
@ibgreen Thank you for your reply, I will think about other solutions, or you have better suggestions:grinning:

**Comment by fuzhenn** [comment]
@ibgreen Thanks for your attention! @maptalks 's maintainer here.

The problem here is in maptalks, all the layer canvases are [pre-rendered off-screen](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#Pre-render_similar_primitives_or_repeating_objects_on_an_off-screen_canvas), where clientWidth and clientHeight are always 0. Meanwhile, [clientWidth](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth) and [clientHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight) are read-only properties, so they can't be updated by upper module.

Thus it would be nice if deck.gl can fall back to canvas's width/height when clientWidth and clientHeight are 0. This should solve this off-screen canvas problem.

Thanks!

**Comment by 1chandu** [comment]
Resolved by #2405

**Comment by Pessimistress** [comment]
Fix published in deck.gl@6.3.3
