### ISSUE TITLE
Icon Layer drawArraysIntacnced error on iOS

### ISSUE THREAD

**Issue by jordmccordgcv** [uber/deck.gl#2324]
Getting an error using icon layers, same error as in the [icon layer example](https://deck.gl/#/examples/core-layers/icon-layer) on iOS, tried on Safari 11 and 12:
First warning (not sure if its related)
```
luma: texture: Texture(https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/../examples/icon/location-icon-atlas.png,512x640) is Non-Power-Of-Two, disabling mipmaping
```
And error: 
```
WebGL: INVALID_OPERATION: drawArraysInstanced: attempt to access out of bounds arrays
```
<img width="992" alt="screen shot 2018-10-02 at 10 26 50" src="https://user-images.githubusercontent.com/39528487/46340585-bbb79a00-c62d-11e8-82ae-c2949f93d39c.png">

**Comment by vitorfranca-tw** [comment]
I have the exact same error

**Comment by vitorfranca-tw** [comment]
You were using another version and it used to work? Which one was it?

**Comment by jarekpelczynski** [comment]
@vitorfranca-tw 
**5.3.4**, but I've recently updated from 6.0.1 (didn't notice that version has an issue – layers not appears on Safari for Desktop). However, 6.1.1 fixes issue on Safari/Desktop but causes on mobile.

**Comment by Pessimistress** [comment]
@jarekpelczynski can you confirm the breakage happened between v6.0 and v6.1?

**Comment by 1chandu** [comment]
> luma: texture: Texture(https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/../examples/icon/location-icon-atlas.png,512x640) is Non-Power-Of-Two, disabling mipmaping

This is because WebGL1 (since it is Safari) doesn't support mip-mapping on Non-power-of-two textures, when we detect this we disable mipmaping and fire above warning, this should not cause any  errors/crashes, and is un-related here.

I was trying to reproduce this on Desktop/Safari, I ran IconLayer on `6.0.3` and `6.1.1` but I am not able to reproduce the issue.

@jarekpelczynski @jordmccordgcv , can you confirm if this is indeed a regression between 6.0.3 and 6.1.1 ?

**Comment by 1chandu** [comment]
@Pessimistress 

Ok, I was able to reproduce this by using iOS-Simulator/Safari and website iconLayer example

With 6.0-release website build : *no crash*
<img width="1000" alt="6 0 0-release-website-no-crash" src="https://user-images.githubusercontent.com/9502731/46448684-efcdb080-c73c-11e8-85b6-3920030e3e94.png">


With 6.1-release website  build : *crash*
<img width="1215" alt="6 1 0-release-website-crash-1" src="https://user-images.githubusercontent.com/9502731/46448691-007e2680-c73d-11e8-9f7d-ad052b1184d1.png">


With latest master branch website build *crash*

<img width="1000" alt="master-website-crash-1" src="https://user-images.githubusercontent.com/9502731/46448697-070c9e00-c73d-11e8-8dc2-816607935b81.png">

Before releasing 6.1 we fixed an issue with attribute-0 here : https://github.com/uber/luma.gl/issues/612

So one possibility is that this fix is not getting applied to iOS browser and it should be. Also another thing I noted, when running on simulator, I see it is using `Apple Software Renderer` instead of GPU. Not sure if this the same case running on a device.

**Comment by 1chandu** [comment]
Making following change in luma.gl fixes the crash (verified using iOS simulator)

https://github.com/uber/luma.gl/blob/d5c43cffd3405a35441f4a7d8e483bff6437b2fd/modules/core/src/webgl/vertex-array-object.js#L21

change `return isWebGL2(gl) || isMobile() || (getBrowser() === 'Chrome');` to `return isWebGL2(gl) || (getBrowser() === 'Chrome');`, i.e. disable this for mobile browsers to match the behavior with Safari desktop.

**Comment by 1chandu** [comment]
@jarekpelczynski @jordmccordgcv @vitorfranca-tw , here is a build of deck.gl website with possible fix, can you please try this out and verify this example works.
CC: @Pessimistress 
https://1chandu.github.io/deck.gl/#/examples/core-layers/icon-layer

**Comment by jarekpelczynski** [comment]
**@1chandu** 
I've monkey-patched in luma.gl in my project and it works

**Comment by 1chandu** [comment]
thanks @jarekpelczynski for verifying

I just published  luma.gl `6.1.1` to include this fix, please upgrade and verify. Re-open if you still see it.
