### ISSUE TITLE
TripsLayer - how can I use it without react?

### ISSUE THREAD

**Issue by elninopl** [uber/deck.gl#2425]
How can I enable animation of TripsLayer without react? TripsLayer example uses React and I really don't know, how to convert it to pure js. Please look at the "animate" function in the code below. I tried to update state of layer but it doesn't work (there is no animation of TripsLayer). I don't know, where should I assign "time" variable. Trails are shown but only on default "currentTime", no animation.

```
import {Deck} from '@deck.gl/core';
import {MapboxLayer} from '@deck.gl/mapbox';
import {TripsLayer} from '@deck.gl/experimental-layers';
import mapboxgl from 'mapbox-gl';

export class App
{
  constructor(props) {
    this.stateInfo = {
      time: 6543
    };
  }

  get state()
  {
    return this.stateInfo;
  }

  animate() {
    var loopLength = 18000; // unit corresponds to the timestamp in source data
    var animationSpeed = 30; // unit time per second

    const timestamp = Date.now() / 1000;
    const loopTime = loopLength / animationSpeed;

    var time = Math.round(((timestamp % loopTime) / loopTime) * loopLength);

    // WHAT SHOULD I DO NOW???

    window.requestAnimationFrame(this.animate.bind(this));
  }
}

window.obido = new App();

var tripsLayerObido = new TripsLayer({
  id: 'trips',
  data: 'trips/tripsKR.json',
  getPath: d => d.segments,
  getColor: d => (d.vendor === 0 ? [253, 128, 93] : [23, 184, 190]),
  opacity: 0.6,
  strokeWidth: 30,
  trailLength: 180,
  currentTime: obido.state.time
});

const LIGHT_SETTINGS = {
  lightsPosition: [-74.05, 40.7, 8000, -73.5, 41, 5000],
  ambientRatio: 0.05,
  diffuseRatio: 0.6,
  specularRatio: 0.8,
  lightsStrength: [2.0, 0.0, 0.0, 0.0],
  numberOfLights: 2
};

export const INITIAL_VIEW_STATE = {
  longitude: 19.93,
  latitude: 50.03,
  zoom: 12.8,
  maxZoom: 19,
  pitch: 60,
  bearing: 0
};


mapboxgl.accessToken = "pk..XXX";

const map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/elninopl/cjnlge6rl094w2so70l1cf8y5',
  interactive: false,
  center: [INITIAL_VIEW_STATE.longitude, INITIAL_VIEW_STATE.latitude],
  zoom: INITIAL_VIEW_STATE.zoom,
  pitch: INITIAL_VIEW_STATE.pitch

});

window.deck = new Deck({
  canvas: 'deck-canvas',
  width: '100%',
  height: '100%',
  initialViewState: INITIAL_VIEW_STATE,
  controller: true,
  onViewStateChange: ({viewState}) => {
    map.jumpTo({
      center: [viewState.longitude, viewState.latitude],
      zoom: viewState.zoom,
      bearing: viewState.bearing,
      pitch: viewState.pitch
    });
  },
  layers: [tripsLayerObido]
});

map.on('load', () => {
  //map.addLayer(tripsLayerObido);
  obido.animate(0);
});

```

**Comment by jianhuang01** [comment]
you can check this example in our release branch. https://github.com/uber/deck.gl/blob/6.2-release/examples/get-started/pure-js/app.js

**Comment by Pessimistress** [comment]
In your `animate` callback you need to construct a new TripsLayer with the updated `currentTime`, then call `deck.setProps({layers: [tripsLayer]})`. See [this example](http://deck.gl/showcases/gallery/hexagon-layer) on how to update a layer.

**Comment by elninopl** [comment]
@Pessimistress your solution works, but are you sure, there is no way to make it more efficient? On each browser redraw it has to parse JSON file and recreate the layer. Is there any chance to just update "currentTime" property?

**Comment by Pessimistress** [comment]
This is by design. deck.gl uses a React-like model where it compares two versions of the same layer (matched by `id`) and only update things that are changed. If you call `setProps({layers})` with a new TripsLayer instance of the same props on every animation frame, there is zero perf impact. In your case, only `currentTime` changes, which will trigger a rerender (intended behavior), but otherwise no data updates.

**Comment by trusktr** [comment]
> If you call setProps({layers}) with a new TripsLayer instance of the same props on every animation frame, there is zero perf impact.

Not necessarily true, because this triggers React diffing mechanisms, and that's not something we may want to have happening at 60fps.

React was designed for casual state changes that aren't for animation (f.e., state changes a class name once, then a CSS animation takes care of the performant animation that follows). But implementing animation in React is actually pretty bad because if we're going to have more complicated scenes, the diffs may add up quickly.

**Comment by trusktr** [comment]
Not only is the `setProps` API disconnected from the layer instances, it is also confusing, especially for someone trying to use the scripting API.

I recommend adding non-React APIs to each class, for animation, and documenting those.

And perhaps, for the benefit of React users, there can be a way to trigger the animations with one-off React state changes rather than animating React state itself.

**Comment by trusktr** [comment]
I forgot another performance sidenote: by create `new Everything` ever frame, objects are also being stacked up for the Garbage Collector, which will increase the likelylihood of jank during animations when the collector has to collect the no-longer-used instances. It would be much better to animate a number property on an instance that is kept around.

**Comment by trusktr** [comment]
The TripsLayer example (from the Examples page) is fairly slow on my relatively modern Pixel 2 phone, but the graphics themselves should in theory run fine (I can play Doom 3 WebAssembly on my Pixel phone at 20fps average, and that's fairly complicated compared to the TripsLayer example).

The above improvements would be great!

**Comment by ibgreen** [comment]
@trusktr Thanks the insightful feedback, highly appreciated!

> A nice change to Deck.gl would be adding non-React APIs for animation to each class (or usable with each class, imperatively), and documenting those.

Let me first say that deck.gl is unlikely to do any deep changes to become an imperative API in the near term, as it is designed from the ground up to support React applications - and our primary internal customer base that is essentially funding deck.gl development is 100% React based.

Within that constraint (trying to set realistic expectations!), making our API easier to use (and more performant!) for "imperative programmers" is definitely something that we'd like to do.

In fact, since deck.gl is attracting many non-React users, and I ran into some pains myself while working on a non-React-based example, I wrote an [Imperative API Improvements RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v7.x/imperative-api-rfc.md) a while ago. It didn't get traction at he time but might be worth taking another look at that based on your feedback.

Not sure how well it is written or how directly it addresses your particular concerns, but any critique (or encouragement!) is welcome.


> [animation]... because this triggers React diffing mechanisms,

This is timely input as we are currently doing a round of improvements on animations 

You are correct. In fact, (when using deck.gl with React) there are in fact three layers involved (react, deck, and luma), and two of those have diffing mechanisms, React and deck.gl.

There are already ways to run animations in deck.gl without triggering the React diffing mechanism, but those are not front and center in our docs. 

There is also a uniform animation system in luma.gl that can run without triggering the deck.gl diffing mechanism (basically involves setting layer props to functions that get evaluated by luma.gl before each animation frame). This animation system has very low overhead (it certainly bypasses React and deck diffing). But it has been kept as experimental in deck.gl as we do not feel happy with the API it provides.
