### ISSUE TITLE
Transition animation will disappear once the map was paned

### ISSUE THREAD

**Issue by EllaZhao** [uber/deck.gl#2564]
I noticed that the animation will disappear once the map was paned, the related code as below I think, the transition option will be set by the default value.

modules/core/src/controllers/controller.js 
``` 
 _onPanMove(event) {
    if (!this.dragPan) {
      return false;
    }
    const pos = this.getCenter(event);
    const newControllerState = this.controllerState.pan({pos});
    return this.updateViewport(newControllerState, NO_TRANSITION_PROPS, {isDragging: true});
  }
```

**Comment by Pessimistress** [comment]
@EllaZhao When you are panning you definitely do not want transition (otherwise the map will be lagging behind you cursor). Viewport transition props only need to be set when you are explicitly triggering it. It works the same way as [this example](https://uber.github.io/react-map-gl/#/Documentation/advanced/viewport-transition).

**Comment by EllaZhao** [comment]
@Pessimistress thanks a lot, it resolved my problem, close it.
