### ISSUE TITLE
Loop of CSS Warnings about `cursor` in Firefox

### ISSUE THREAD

**Issue by nchevobbe** [uber/deck.gl#2618]
#### Description
Firefox Devtools console is spammed with `Error in parsing value for ‘cursor’. Declaration dropped.` messages.

#### Repro Steps
1. Visit https://deck.gl/showcases/gallery/boiler-plate on Firefox
1. Open the console, and enable the "CSS" filter if it wasn't
1. Close devtools
1. Reopen the console

`Error in parsing value for ‘cursor’. Declaration dropped.` is displayed, and the repeat counter keeps updating.

#### Environment (please complete the following information):
 - Framework Version: unknown
 - Browser Version: Firefox 66
 - OS: OSX

---

In the page code, I'm seeing:
```js
this.canvas && (this.canvas.style.cursor = this.props.getCursor(this.interactiveState))
```

A quick evaluation in the console indicates that `this.props.getCursor(this.interactiveState)` returns `"-webkit-grab"`, which is not supported by Firefox, hence the warning message.
Then my guess is that this code is executed in a requestAnimationFrame callback or another loop, triggering the warning message on each iteration.

A quick test indicates that the following: `data:text/html,<meta charset=utf8><h1 style="cursor:grab">grab</h1><h1 style="cursor:grabbing">grabbing</h1>` does show grab/grabbing cursors in Chrome, so maybe we don't need the `PREFIX` part in https://github.com/uber/deck.gl/blob/049b6836f394507988853713f02ed21327476753/modules/core/src/lib/deck.js#L43-L44 ?

I'd be happy to create a PR if you can confirm that I can get rid of them (I only tested Chrome Canary, and I don't know what browser version you want to support).

**Comment by mccalluc** [comment]
More context: 
- I had filed #2597 earlier, and [another one](https://bugzilla.mozilla.org/show_bug.cgi?id=1521245) with firefox.
- @nchevobbe looked into the firefox issue, and judged that it's really a problem with deck.gl, and filed this issue in turn.
- Meanwhile @Pessimistress did make a PR that should fix the examples (#2608)... but that seems to be looking at something different than what @nchevobbe noticed.
- I'm pretty sure that the problem is not limited to iframes: My own code seems to hit the same infinite loop on Firefox, with no iframes. I see the warning being issued continuously in the console: I believe it comes from deck.js:534
```
    value: function _updateCursor() {
      if (this.canvas) {
        this.canvas.style.cursor = this.props.getCursor(this.interactiveState);
      }
```
In the debugger: `this.props.getCursor(this.interactiveState): "-webkit-grab"`

The call stack at this point:
```
_updateCursor (deck.js#536)
_onRenderFrame (deck.js#678)
onRender (animation-loop.js#196)
_renderFrame (animation-loop.js#259)
```
