### ISSUE TITLE
Non-uniform scale for MeshLayer

### ISSUE THREAD

**Issue by Cmdu76** [uber/deck.gl#2642]
#### Target Use case
In my use case, I have a lot of objects I want to render as cube using the MeshLayer but each object as different dimensions, so I use a CubeGeometry with size 1,1,1 and I want to scale each side by its real size. I tried to modify the MeshLayer vertex and class to add scale as instanced parameters and it worked well. But when I change the yaw, the mesh is really weird looking, I guess it's related to the project_* functions. (If the feature is rejected, can someone just tell me what is the way to go ?)

Non-uniform scale is really important to me and I'm sure it will be too for many others in the future. It allows using CubeGeometry and give a really different visual which might be very important.

#### Proposed feature
Adding per-mesh non-uniform scale along x,y,z.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by ibgreen** [comment]
We have been discussing supporting a full 4x4 matrix for each element/instance in the mesh layer for maximum generality (rather than add more and more parameters for such use cases).

That would allow you to any specify non-uniform scaling, skew etc in addition to translations and rotations. 

If we do implement this, there would be some extra work for the app in such cases: 4x4 scaling matrices are pretty easy to set up manually but you might want to use a math library like math.gl or gl-matrix to build those matrices (especially if combining the scaling with additional operations).

**Comment by Pessimistress** [comment]
This is addressed by https://github.com/uber/deck.gl/pull/2685
