### ISSUE TITLE
Add Flow type definitions

### ISSUE THREAD

**Issue by NameFILIP** [uber/deck.gl#2645]
Are there any plans for doing this? It would be useful to developers to catch typos and guarantee they are using the library correctly.

**Comment by NameFILIP** [comment]
by choosing either flow or typescript you'll be safer than without them, so not tying to a specific technology is more of a disadvantage rather than a benefit. You can always strip the types when you publish it so that consumers are not tied to the specific technology.

Alternatively, you can provide definitions for only the public API which will give type safety to consumers, but will not help you a lot.

**Comment by lxe** [comment]
You can add them to https://github.com/flow-typed/flow-typed

**Comment by cain-wang** [comment]
Or probably we can wait for a little bit and then everybody will move to TypeScript, then we only need to provide one type def :)

https://jaxenter.com/yarn-v2-roadmap-154962.html

**Comment by NameFILIP** [comment]
don't like the waiting part, but I'd love if the world abandoned any of these and only had one JS type system

**Comment by vicapow** [comment]
I'm not sure waiting to rewrite all of our code is really practical solution here.

**Comment by ibgreen** [comment]
> by choosing either flow or typescript you'll be safer than without them

I have tried to explain my position on this topic to "flow and typescript proponents" a couple of times with rather mixed success, but I'll give it a try:

As much as I would love types, a type system is a non-starter because of how I view open source code. I do not see our open source code as just "an API and an npm module" that we publish for people to reuse (which we can then write in any JS dialect/language we choose, as long as we babel-transpile it to ES5/ES6/... before we publish).

I see what we offer as MIT licensed archive of very high quality, standard ES6+ source code that people can cut and paste pieces from and reuse in their own projects. 

With this view, each non-standard syntax we adopt dramatically reduces the number of people who can just copy and paste our code into their projects. 

I personally use source code from other MIT projects in this way, and think it is one of the great benefits of the open source model/community. However I always "move on" when I find the code I am interested in was written in some non-standard format, whether it be coffeescript, flow etc.

> I'd love if the world abandoned any of these and only had one JS type system

Amen.

Adding types would seem like a logical next step in the evolution of the JS standard?

**Comment by NameFILIP** [comment]
What are the use-cases for people to cut and paste pieces of deck.gl code?

Types can help you to have "very high quality" code (15% reduction of bugs https://blog.acolyer.org/2017/09/19/to-type-or-not-to-type-quantifying-detectable-bugs-in-javascript/).

And if you see a lot of value in having standard ES6+ source code you can get it in one step like: 

```
babel --plugins @babel/plugin-transform-flow-strip-types **/*.js
```

which you can have in the package.json scripts.

**Comment by ibgreen** [comment]
Since this has become a discussion around adopting flow inside deck.gl will close this issue - we'll open a new issue focused on adding flow type definitions.

I'll add a final response, happy to discuss more in person if desired.

**Comment by ericsoco** [comment]
@ibgreen 's made his case pretty clearly IMO.

That said, I'll add one more perspective:

Adding Flow types to an existing codebase is resource-intensive and onerous and does not guarantee type safety. Partial static type coverage can be dangerous in its own right, allowing authors to make assumptions about safety that are ensured by the type checker that can be controverted at runtime.

You can list me generally in the "Flow proponents" category, but having gone far down the path of adding Flow types to an existing codebase, I can say with certainty that it's not an unqualified win.

**Comment by ibgreen** [comment]
Thanks for your input. I fully admit that my reluctance comes down to my philosophy and I know from multiple interactions that flow/typescript proponents find my position hard to understand.

That said, realistically, a change will only happen if the folks **actually contributing to deck.gl** really want to use types, and then the choice of which type system to use depends on how dominant one of these solutions becomes, and what the team wants e.g. typescript vs flow etc.

> Types can help you to have "very high quality" code (15% reduction of bugs 

Thanks, I get this type of links every time the conversation comes up. Have done decades of C++ template meta programming, type systems are not something new. If I felt types would make a big difference, we would already have adopted them.

**Comment by ibgreen** [comment]
> What are the use-cases for people to cut and paste pieces of deck.gl code?

Good question! There is a huge amount of potentially reusable code in our frameworks, including: geospatial coordinate projection classes that use advanced optimization techniques, event handling controllers, shader modules, code that sets up data for GPU, management of attribute transitions, a prop type system, a component lifecycle management system, many code examples, and layer subclass examples etc.

I have personally built up entire frameworks (e.g. [loaders.gl](https://github.com/uber-web/loaders.gl) and math.gl) in short time by cutting, pasting code and repurposing code that was almost but not quite reusable from other places. 

I'd love it if others did the same with our code.

Also a number of users of deck.gl don't use npm and babel, they use e.g. scripting versions of deck.gl.

**Comment by ibgreen** [comment]
@NameFILIP 	#2647
