### ISSUE TITLE
How to manipulate viewState with controller still working in react applications?

### ISSUE THREAD

**Issue by hijiangtao** [uber/deck.gl#2692]
I checked existing issues and searched "deck.gl viewState change" but still couldn't get solution.

## Problem description

I have a menu, which can help me switch layer between ScreenGridLayer, TripLayer, etc. All things works fine except the view state. I may want to change view state when different layer is loaded since I need to visualize different data in various country, but it seems I can't change it to some specific view state and keep the controller still working at the same time.

## The ways I tried

1. I return following JSX object in my react component `render()` method (I may change `initialViewState` dynamically), the viewState will not change since I put the object in `initialViewState` props, obviously.

```
<DeckGL
    initialViewState={initialViewState}
    // viewState={initialViewState}
    controller={controller}
>
```

2. I tried the get DeckGL instance and manipulate with `setProps` method:

```
// event handler
this.deckglIns.setProps({
   viewState: LAYER_CONFIGS[layer].INIT_VIEW_STATE
})
 
<DeckGL
    ref={e => this.deckglIns = e}
>
```

According to the documents, DeckGL can access all public methods from deck:

> All Deck methods are available on the DeckGL component. from http://deck.gl/#/documentation/deckgl-api-reference/react/deckgl?section=render-callbacks

But apparently `setProps` is not one of them, since DeckGL didn't define this method (https://github.com/uber/deck.gl/blob/6.4-release/modules/react/src/deckgl.js) while deck did (https://github.com/uber/deck.gl/blob/6.4-release/modules/core/src/lib/deck.js#L179-L215)

3. I put viewState object into `viewState` prop, the controller can not manipulate the map anymore, since viewState is always a fixed object forever:

```
<DeckGL
    viewState={initialViewState}
    controller={controller}
>
```

The thing is I want to change viewState only when my layer changed, and then let controller keep working and response to user mouse events. Any ideas on it? Thanks very much.

**Comment by hijiangtao** [comment]
It seems I can handle this problem with the help of `onViewStateChange`, according to example https://github.com/uber/deck.gl/blob/master/docs/api-reference/view-state-transitions.md , but I couldn't find a way to solve it first since I focus on viewport changing example https://github.com/uber/deck.gl/blob/master/examples/gallery/src/viewport-transition.html 

Hope other developers can find something useful from my description when they reach here.

So, one more question, is it possible to implement `setProps` for DeckGL?

**Comment by ibgreen** [comment]
> So, one more question, is it possible to implement `setProps` for DeckGL?

It is indeed available, just not in the way you are asking for: When you rerender your `DeckGL` component with updated props, you are implicitly calling `setProps` with the new props. It may help you to consider that React applications essentially set all the props of all their components every time something changes in the app.

If you are more comfortable with an imperative programming style (e.g. `deck.setProps()`) then you should probably be using the pure JavaScript version of deck.gl.

I do agree it wouldn't hurt make a small change to the doc section you quote.

Finally for your use case, I'd recommend using the `viewState` prop instead of `initialViewState`, since you want more control over the viewState than the built-in handling provides. You'd keep a state variable that you update on `onViewStateChanged` or when you wanted to programmatically change it, and pass it into `DeckGL`, and make sure you have a working React app setup so that you rerender your React component tree when state changes.

**Comment by hijiangtao** [comment]
Yeah, I thought `setProps` may meet my requirements in `DeckGL` first, and I did see the description and mistook it as a public method in `deck`.

> All Deck methods are available on the DeckGL component.

I resolved it with the same approach you mentioned above, and thanks very much. I am glad to raise a PR to make documents in describing **DeckGL Methods** more clearer.

**Comment by hijiangtao** [comment]
Merged and closed.
