### ISSUE TITLE
Deck.gl not showing up

### ISSUE THREAD

**Issue by sushmitsarmah** [uber/deck.gl#2696]
Sorry this is a very basic question but I am not sure where else to ask.

My map is not showing up. I have tried everything and followed the examples but it just shows up as blank. My mapbox token is active and I checked it. But still nothing.

Here is the stackoverflow question I raised which has my code. Absolutely basic.

[https://stackoverflow.com/questions/54572431/i-was-trying-out-ubers-deck-gl-by-adding-the-component-to-my-react-app-but-not](https://stackoverflow.com/questions/54572431/i-was-trying-out-ubers-deck-gl-by-adding-the-component-to-my-react-app-but-not)

Any help to set this up would be appreciated

**Comment by IgorWilbert** [comment]
Hi @sushmitsarmah ! No problem, we're happy to help! Could you please give more details like the version of React and npm? Sometimes such issues are related to the setup and not the code.

**Comment by hijiangtao** [comment]
@sushiNg According to your description in stackoverflow (since there's not too much information), I suspect if you create a HTML file contains `root` element, like this: 

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            #root {
                width: 100%;
                height: 100%;
            }
        </style>
    </head>
    <body>
        <div id="root"></div>
    </body>
</html>
```

You can put your code on codepen or some online editors, so that we can help you more specifically. 

Besides, I recommend you read codes in this folder https://github.com/uber/deck.gl/tree/master/examples/get-started rather than the codes in documents. Sometimes, codes in documents is for explaining concepts, and not ready for running.
