### ISSUE TITLE
How to disable debug mode?

### ISSUE THREAD

**Issue by ParryQiu** [uber/deck.gl#2730]
Take the liberty to ask, how to disable the debug mode?

I looked at the source code and need to set it through localStorage?

And in the Angular 6 project, there will be the following loading errors.

`Uncaught ReferenceError: global is not defined`

Although it can be solved by add `(window as any).global = window;` in Angular 6 project polyfills.ts file.

**Comment by ibgreen** [comment]
>  Take the liberty to ask, how to disable the debug mode

What is it that you want to disable? Initially it should have a log.priority of 0 so nothing should be logged.


> I looked at the source code and need to set it through localStorage?

You can import the `log` symbol, it is an instance of the probe.gl `Log` class

Or you can use the browser console, it is exported on the global variable `deck`:

```
deck.log.enable(false);
deck.log.priority = 0;
```

Those statements automatically save their values in local storage (so that they persist across reloads) you don't need to worry about that.

>  Uncaught ReferenceError: global is not defined

This should not happen, assume some interaction between deck and angular initialization, would be good with more information or a codepen so we can debug and fix.

**Comment by ParryQiu** [comment]
Thanks very much @ibgreen .

I want to turn off debug mode (The console does not output debugging information.) when I initialize the call to deck.gl.

It seems that it can only be turned off by importing probe.gl Log.

The project is running in Node.js mode with two error screenshots for reference.

![error 1](https://image.devopen.club/deckgl-error-1.png)

![error 2](https://image.devopen.club/deckgl-error-2.png)

**Comment by ParryQiu** [comment]
This error is not a big problem and can be solved by add `(window as any).global = window;` in Angular 6 polyfills.ts file.

Maybe you can close this issue, Thanks again.

**Comment by ibgreen** [comment]
Are you importing `luma.gl/debug`? If you do, just drop that line. If not, you should not be hitting that code path... We don't import `WebGLDebug` utils by default, in order to minimize bundle size in production...

Are you using the latest version of luma.gl, 6.x? If not that could explain why this happens.
