### ISSUE TITLE
GeoJsonLayer (points) in standalone: does it work?

### ISSUE THREAD

**Issue by geoglrb** [uber/deck.gl#2731]
#### Description
I have no problem getting the GeoJsonLayer (polygons) to render, either with your example Vancouver land values GeoJSON or with others of my own. But when I have tried several GeoJSONs (from various sources, including a simple one I made as a test) that have only points, I can't get them to render. I'm not sure if this is a bug... or just an indirect request for more documentation / another example! Thanks.

#### Environment:
 deck.gl 6.3.0 and 6.0.0
 Current Firefox and Chrome
 MacOS 10.14.3

#### Logs
Don't seem to be any relevant warnings in the console logs.

**Comment by xintongxia** [comment]
I just tried render a simple GeoJSON Layer with points only, it works fine for me. 

It is also possible that the data is rendered, but not visible enough because of the small radius. Could you try to give a big radius or `radiusScale` for points feature?

```
new GeoJsonLayer({
  ...,
  radiusScale: 10,
  getRadius: d => 100
})
```

Also you can check more options in [GeoJSON Layer](https://github.com/uber/deck.gl/blob/master/docs/layers/geojson-layer.md) 

The feature I used is 
```
{ 
  "type":"Feature",
  "geometry": {
    "type":"Point",
    "coordinates":[-122.44477272033691,37.79906910652822]
  }
} 
```

**Comment by geoglrb** [comment]
Ah! Yes, that helps. Markers were too small. Appreciate your time here.

**Comment by chriszrc** [comment]
My icons were blank too, circles and text worked fine. Seems older examples have `getSize` whereas the latest docs indicate to use `getIconSize`. Then they appeared, huzzah
