### ISSUE TITLE
Deck.gl mutates color variables

### ISSUE THREAD

**Issue by manassra** [uber/deck.gl#2732]
#### Description

In a project where we use DeckGL, @rolyatmax noticed that `getFillColor` wasn't behaving correctly. When using a color variable, and spreading into the function we see this artifact. 
```
const COLOR = [229, 73, 55];
// later...
getFillColor: () => [...COLOR, 20]
```
![image](https://user-images.githubusercontent.com/1332450/53664657-f5f98780-3c1d-11e9-9aef-122332cc0f08.png)

As it turns out, color accessors mutate the color array and set an alpha value if it is missing. For example:
```
const COLOR = [0, 1, 2]
// later...
getLineColor: () => COLOR
// then...
console.log(COLOR) // [0, 1, 2, 255]
```

#### Repro Steps
* Declare an RGB color array as a variable
* return this variable in `getLineColor`
* spread and set a value for the alpha chanel, and return in `getFillColor`

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0] 
6.3.4
 - Browser Version: [e.g. Chrome 71.0]
72.0.3626.119 
 - OS: [e.g. Mac OS X 10.4]
10.14.3

**Comment by rolyatmax** [comment]
It also looks like it's assuming the color array is size 4 and loading the entire array into the color attribute's buffer, and then reading it out in size 4. A color value that looks like `[R, G, B, A, X]` will result in an attribute buffer that looks like `[R, G, B, A, X, R, G, B, A, X, R, G, B, A, X]`. This gets cut up into vec4s and passed to each vertex. So the colors look like:

```
RGBA
XRGB
AXRG
BAXR
```

That's why we've got the funky rainbow color scheme above.

**Comment by manassra** [comment]
Yeah, I wonder whether we should either:
1) Only slice to the first 4 values if the color array is larger than RGBA
2) Pass it through and warn the user
