### ISSUE TITLE
getViewport is a method of ViewManager, not of View

### ISSUE THREAD

**Issue by mccalluc** [uber/deck.gl#2748]
#### Description
The [docs](https://github.com/uber/deck.gl/blob/master/docs/developer-guide/views.md#projecting-coordinates-using-views) say:
> While a View by itself does not contain enough information to support projection and unprojection of coordinates, calling `view.getViewport({viewState, width, height})` ...

... except `getViewport` is a method of [`ViewManager`](https://github.com/uber/deck.gl/blob/171c27d802e5ce9f0ca5f2e4afb9b74df25738c8/modules/core/src/lib/view-manager.js#L126) not of `View`. When I try to call `getViewport` from a view, I get `view.getViewport is not a function`.

(Probably a documentation issue rather than a bug?)

#### Repro Steps
```javascript
const view = new deck.OrthographicView();
view.getViewport();
```
https://codepen.io/mccalluc/pen/LaRxvL?editors=1010

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.4.1]
 - Browser Version: [e.g. FF 65.0]
 - OS: Mac OSX

#### Logs
```
TypeError: view.getViewport is not a function
```

**Comment by ibgreen** [comment]
@mccalluc Yes this looks like a doc bug.

Looks like this was renamed to `View.makeViewport({width, height, viewState})`. 

The function mints a new Viewport (which is why it was renamed as `getViewport()` makes it sound like it just returns an existing viewport, a much cheaper operation).

But the change didn't make it into the docs.

Want to put up a PR?
