### ISSUE TITLE
Expected behavior for min/maxRadiusPixels for COORDINATE_SYSTEM.IDENTITY

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#2824]
#### Description

Via the `radiusMaxPixels` API we can cap the largest size of circles.
This works well for the default (web-mercator) projection mode:
http://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer

But not in the COORDINATE_SYSTEM.IDENTITY mode.
https://codepen.io/gnavvy/pen/NJOzZO
^ basic setup (not sure how to simulate the scrollZoom, and need help to get viewState to work in codepen.)

#### Environment (please complete the following information):
 - Framework Version: deck.gl v6.4.7

**Comment by gnavvy** [comment]
@colafly

**Comment by Pessimistress** [comment]
The issue lies in the overload of the term "pixels".

```glsl
  float outerRadiusPixels = clamp(
    project_scale(radiusScale * instanceRadius),
    radiusMinPixels, radiusMaxPixels
  );
```

Here, we are clamping a radius in the world space (returned by `project_scale`) with limits in the screen space (`radiusMinPixels` and `radiusMaxPixels`).

In MapView, a "pixel" on the WebMercator plane (i.e. 1 unit in the world space) is roughly a pixel in the screen space after projection. In OrthographicView, 1 unit in the world space maps to different screen space sizes based on the zoom level. This fact will not change unless we change what `COORDINATE_SYSTEM.IDENTITY` means.

My proposal is that we introduce an additional uniform that is the scaling factor for converting world pixels to screen pixels. In MapView it is `1`, and in OrthographicView it is `zoom^2`.

@ibgreen @tsherif

**Comment by ibgreen** [comment]
> My proposal is that we introduce an additional uniform that is the scaling factor for converting world pixels to screen pixels. In MapView it is 1, and in OrthographicView it is 2^zoom.

Yes... given the complexity of the project module, and the "risks" associated with changing it, doing a lightweight, non-breaking change, perhaps like the one you propose sounds like a good idea.

We should probably just do a quick review of the proposal before we start to make sure we all have thought it through and it doesn't lock us down compare to long-term plans etc.

> The issue lies in the overload of the term "pixels".
> This fact will not change unless we change what COORDINATE_SYSTEM.IDENTITY means.

Naively, one would think that the combination of "deltas" in IDENTITY and a viewport would result in unambiguous definition of pixel sizes. If not it will be good to make clear if/why this is not the case...

For the longer term, articulating and documenting what distances/sizes means in IDENTITY could be a great first step. Documenting both how they work in the current implementation, and also if we would like to redefine that.

**Comment by ibgreen** [comment]
Tracker for term plans in #2828

**Comment by Pessimistress** [comment]
> Naively, one would think that the combination of "deltas" in IDENTITY and a viewport would result in unambiguous definition of pixel sizes. If not it will be good to make clear if/why this is not the case...

There is no scaling applied to offsets/sizes/distances in IDENTITY mode, and this is consistent with documentation. 1 unit from user input translates to 1 unit in the world space.

**Comment by ibgreen** [comment]
> and this is consistent with documentation. 

I feel it would be beneficial to work through this terminology as a group, to ensure we talk about same things when we talk things like world space.

As an example, in generally accepted 3D terminology, user input is by definition world space, there is no "translation". In the long lat case this gets confused because we talk about a post non-linear projection "mercator world space" (which is really a shader working space which to complicate matters is not fixed but scale dependent as a result of a misguided attempt from my side to manage precision issues). 

Scanning through the [Coordinate Systems](http://deck.gl/#/documentation/developer-guide/coordinate-systems?section=about-geospatial-positions) article I do not find any clear user facing statements around the mapping of IDENTITY to pixels.

Clarifying these things, (and if possible clearly defining the shader working space in each case), would very helpful (at least to me), and are part of the reason why I am suggesting a refresh/redefinition/refactor of the project module.
