### ISSUE TITLE
Any documents about the change of `changeFlags` propperty in `updateState` lifecycle?

### ISSUE THREAD

**Issue by hijiangtao** [uber/deck.gl#2849]
Hi, there. I used to utilize `changeFlags` property inside `updateState` lifecycle to do some operations, however, I noticed the properties inside it had changed with recent update.

All the properties used to return a boolean value but now will hint following information:

```
dataChanged: "A new data container was supplied"
propsChanged: "props.initialViewState changed shallowly: [object Object] -> [object Object]"
propsOrDataChanged: "A new data container was supplied"
somethingChanged: true
stateChanged: true
updateTriggersChanged: false
viewportChanged: false
```

So what's the new data container? I found the document is still the same as it used to be http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=updatestate

Thanks.

**Comment by ibgreen** [comment]
These strings are not documented. The reasons we use strings instead of booleans for those flags is simply to facilitate debugging. 

If you set `deck.log.priority = 1` (or 2, 3, 4) we print increasingly detailed info using those flags among other things.

You can search for these strings in the deck.gl code using github: https://github.com/uber/deck.gl/search?q=new+data+container+was+supplied&unscoped_q=new+data+container+was+supplied

As you can see the changed "data container" just refers to the layer's `data` prop having changed. 

If you think the message is confusing and would like to change it to say `props.data has changed`, feel free to open a PR.

**Comment by hijiangtao** [comment]
@ibgreen How to set `deck.log.priority = 1` manually in codes? Thanks.

**Comment by ibgreen** [comment]
We usually set it manually in browser console (since we never want it on by default), but if you want to set in code, `deck.log` is the same log object that is exported by deck.gl:

```
import {log} from `@deck.gl/core`;
log.priority = 1;
```
