### ISSUE TITLE
TileLayer does not support COORDINATE_SYSTEM.IDENTITY?

### ISSUE THREAD

**Issue by mccalluc** [uber/deck.gl#2931]
It looks like `TileLayer` assumes x and y are lat and long, and if they are out of range, it fails.
I'm starting with this:
```javascript
    return new TileLayer({
      id: 'tile-layer',
      coordinateSystem: COORDINATE_SYSTEM.IDENTITY,
      getTileData: ({ x, y, z }) => {
        console.log(x, y, z);
      },
    });
```
and I hit this error:
```
deck: error while initializing TileLayer({id: 'tile-layer'})
 Error: invalid latitude
    at assert (assert.js:3)
    at lngLatToWorld (web-mercator-utils.js:26)
    at getTileIndices (viewport-util.js:47)
    at TileCache.update (tile-cache.js:72)
    at TileLayer.updateState (tile-layer.js:112)
    at TileLayer._updateState (layer.js:799)
    at TileLayer._initialize (layer.js:767)
    at LayerManager._initializeLayer (layer-manager.js:700)
    at LayerManager._updateSublayersRecursively (layer-manager.js:631)
    at LayerManager._updateLayers (layer-manager.js:581)
```
It looks like [`viewport-util.js`](https://github.com/uber/deck.gl/blob/76291a07239343e9fe1de4e57b08317706facf8c/modules/geo-layers/src/tile-layer/utils/viewport-util.js#L44) assumes the coordinates are geographic:
```javascript
const [minX, minY] = lngLatToWorld([bbox[0], bbox[3]], viewport.scale).map(pixelsToTileIndex);
```
- Is my understanding of the problem correct?

I'm planning to copy out just these files, and see if adding a check for `IDENTITY` fixes this.
- Does that seem like a reasonable approach, and would you like a PR if I can get it working?

**Comment by 1chandu** [comment]
> Is my understanding of the problem correct?

Yes, AFAICT yes, this layer works with geographic data only CC: @Pessimistress 
Can you explain your use case to use non geographic data?

**Comment by Pessimistress** [comment]
The TileLayer is designed around the geospatial use case. The tile indices (`x, y, z`) are defined by the OSM tile system. What do you expect the indices to be in the identity coordinate system?

**Comment by mccalluc** [comment]
Thanks - Good point.

Use case: I'm working with microscopy data, using deck.gl polygon and scatterplot layers to highlight features, but the image itself just an SVG `<image>` I position underneath, and I update the `viewBox` as the user changes the view. Right now I'm subsampling the pixels, but to really show all the data which is available, I will need to use a tile server. (I'll be using a [HiGlass](http://higlass.io/) server, probably: It takes an x/y/z like OSM, but returns a matrix rather than an image, so the color scale could be adjusted on the client side, for example.)

I think what I'll need to do is pass an additional parameter in the constructor: The zoom level at which x and y match image coordinates... `ceil(log2(max(width, height)))` or something like that.

I can see that this might be a very specialized use, but it's good to know I'm not missing something. Thanks!

**Comment by tgorkin** [comment]
Interesting use case!  When you get it working, let us know if its something we could possibly share on our website to showcase deck.gl.  

Closing this issue, but please re-open to discuss if you feel the TileLayer API should be extended.

**Comment by ilan-gold** [comment]
Hello again!  I work in the same lab as Chuck and I have gotten this working (i.e using a TileLayer with non-geospatial image tiles and `COORDINATE_SYSTEM.IDENTITY` ).  I did so through editing a few functions that are used by the in the process of generating a TileLayer, mainly surrounding getting bounding boxes and the like (in https://github.com/uber/deck.gl/blob/master/modules/geo-layers/src/tile-layer/utils/tile.js and https://github.com/uber/deck.gl/blob/master/modules/geo-layers/src/tile-layer/utils/viewport-util.js).  We don't use our own tiling server (yet), but are simply relying on jpeg files generated by DeepZoom in that tiling format.    

The changes are not considerable, but if this is something you'd like in deck.gl, I can try to make a pull request here.  Otherwise, I think we'd release our own little stand-alone package with the layer + utils.   If there is another way forward, though, please let me know!

**Comment by Pessimistress** [comment]
@ilan-gold PRs are always welcomed! As long as we can define the tiles in a consistent way, I don't see why we shouldn't support the non-geospatial use case. It's also worth considering exposing the tiling logic to the users of the layer so that they can define their own.

**Comment by ilan-gold** [comment]
@Pessimistress I took some time to think this over (and also went on vacation for a while), and I think you are correct - we should expose the logic of the tiling, via both `getTileIndices` for use on https://github.com/uber/deck.gl/blob/master/modules/geo-layers/src/tile-layer/utils/tile-cache.js#L52 and `tile2boundingBox` for use on https://github.com/uber/deck.gl/blob/e2b76a3fe23e43cb6a516b065a762d72b6a40b2c/modules/geo-layers/src/tile-layer/utils/tile.js#L20.  Lastly, to where do you think the `TileLayer` code should be moved, since it is under `geo-layers` now but will no longer be exclusively for that?

**Comment by Pessimistress** [comment]
> do I need permission to contribute to the repo?

No. If you fork this repo and push a branch to your fork, you can open PRs from your branch to deck.gl master.

> to where do you think the TileLayer code should be moved, since it is under geo-layers now but will no longer be exclusively for that?

Depending on its maturity, we can consider moving a very generic version of this layer to the core layers (`@deck.gl/layers`) module. `geo-layers` can still export a geospatial version that implements `getTileIndices` etc. to the OSM tile specs.

**Comment by ilan-gold** [comment]
Thanks for that - I have never done this sort of thing before so I will fork it then.  As for the location, I think that is a very good idea.  Thanks!

**Comment by ilan-gold** [comment]
Hello @Pessimistress, I am wondering if you might have a sense of what the API should be: which of the core layer and the geo layer be called `TileLayer` and which should be called something else (like `ImageTileLayer` or `GeoTileLayer`)?  Or should they both be renamed or both called `TileLayer`?  My inclination was to call the `geo-layers` version `MapTileLayer` and the `core` version `TileLayer` but figured I should check since this is essentially an API change (which would require updating docs etc.).

**Comment by Pessimistress** [comment]
It would be a breaking change if we rename the one in geo-layers, so that needs to wait till the next major release.

We may call the one in core layers `BaseTileLayer` for now?

**Comment by Pessimistress** [comment]
Closing with the addition of `BaseTileLayer`, scheduled for v8.1.0. Thanks @ilan-gold!
