### ISSUE TITLE
Low performance from isFlattenable / baseFlatten

### ISSUE THREAD

**Issue by dcposch** [uber/deck.gl#301]
Deck.gl version: 3.1.1
Chrome version: 55
System: 2016 12" Macbook

I'm using deck.gl to draw a zoning map of San Francisco. The dataset is not large, only 1600 polygons and a total of 200k vertices.

With picking enabled, I'm getting a blazing 3 FPS.

It looks like that's totally CPU bound. GPU is fine. Most of the scripting time is spent in isFlattenable and baseFlatten:

![image](https://cloud.githubusercontent.com/assets/169280/22186119/6b10b362-e0a5-11e6-99cb-fd027575eea2.png)

Thoughts?

**Comment by shaojingli** [comment]
Hi @dcposch 

From you trace, it seems that most of the time is being spent in lodash.flattendeep function... The bad news is that we don't control this as it's from the lodash module but the good news is that we are currently working on a new choropleth/polygon layer for the next release of deck.gl so that its performance will be improved significantly @ibgreen

BTW, from the trace, I see that getError takes significant amount of time... are you using deck.gl in the debug mode?

**Comment by dcposch** [comment]
> BTW, from the trace, I see that getError takes significant amount of time... are you using deck.gl in the debug mode?

I was running in debug mode, but for my actual site deployment I'm using browserify with `NODE_ENV=production`.

About to send a PR that makes `calculateColors` populate a Uint8Array directly instead of creating a huge tree of JS arrays and then calling flatten. Should run faster and make fewer memory allocations.

**Comment by ibgreen** [comment]
> With picking enabled, I'm getting a blazing 3 FPS. It looks like that's totally CPU bound. GPU is fine. Most of the scripting time is spent in isFlattenable and baseFlatten:

@dcposch Normally, geometry should only be regenerated when a new data array is being passed. Picking works through an extra GPU render pass and should not involve JS. Are you perhaps changing the data array during picking (e.g. trying to change the color of a polygon to show that it is selected)? Also consider other props that might trigger regeneration, accessors, updateTriggers etc. It might be helpful to set `deck.log.priority = 3` in the debugger, and see if you can get some trace on change detection.

If so, a better approach could be to keep your first choropleth unchanged, and overlay a second choropleth layer showing just the selected polygon, on top of the first layer. 

> we are currently working on a new choropleth/polygon layer for the next release of deck.gl so that its performance will be improved significantly

Indeed, just opened #303 on `dev` that improves geometry generation performance for flat `PolygonLayer`s with ~5x compared to `ChoroplethLayer`. But again it should not matter, since geometry creation should be a one time thing.

```
npm run bench
deck.gl 3.1.0-beta.10 - set deck.log.priority=2 to trace attribute updates
Starting bench...
ChoroplethLayer#initialize x 11.58 ops/sec ±4.85% (34 runs sampled)
PolygonLayer#initialize (flat) x 58.32 ops/sec ±2.16% (60 runs sampled)
...
```

**Comment by dcposch** [comment]
@ibgreen geometry generation is a one-time thing. Flatten is being called from within `computeColors`, and I'm using picking to highlight elements. Specifically, I'm using onHover to change the color of the hovered choropleth element.

When moving my mouse quickly, this means `computeColors` gets called once per frame. This used to be slow, but on my branch it now runs smoothly: #302

**Comment by ibgreen** [comment]
@dcposch Thanks for sharing your site, looks great with the fix! I suppose   

>  geometry generation is a one-time thing.

Understood. You are just triggering the recalculation of one of the attributes (`colors`). It is still a pretty big array to recalculate on every mouse move, but it seems performance is good enough with the fix so you may not need to go the dual layer route (Thanks for sharing your site by the way, it looks great!)

Will comment on the PR separately.

**Comment by ibgreen** [comment]
@dcposch I believe we have achieved much better attribute update performance in the upcoming deck.gl v4 version. Since you have already started testing that version, I will close this ticket. Let's open new tickets if things don't perform in v4, and we'll get it sorted.
