### ISSUE TITLE
Arc layer over the pacific ocean

### ISSUE THREAD

**Issue by PassionVegetable** [uber/deck.gl#3252]
I am having trouble plotting arcs over the pacific ocean. For instance, if I have a start point at Japan and end point at San Francisco, I would like it to go over the pacific ocean, and not the other way around Europe. How do I implement this? 
Currently using React and the most basic code from the example.
![Pic 2019-06-19](https://user-images.githubusercontent.com/35594466/59753137-16754c80-92b6-11e9-9483-f979e348f0ef.png)

**Comment by Pessimistress** [comment]
You can try setting `wrapLongitude: true` on the layer.

**Comment by PassionVegetable** [comment]
Thanks! I'll work with that for now, even though it isn't perfect in some cases (eg Singapore to Vietnam)
![Pic 2019-06-20](https://user-images.githubusercontent.com/35594466/59912929-b6171400-9449-11e9-8f02-a0252be4dce8.PNG)

**Comment by Pessimistress** [comment]
The robust way to implement this is to:

- Set `wrapLongitude` to `false` (the default)
- Modify your data so that an arc always takes the shorter route. For example, if you have two cities `[-122, 37]` and `[139, 35]`, the arc will span `139 - (-122) = 261` degrees. By adding `360` to the first longitude (`[238, 37]`), your arc will span `238 - 139 = 99` degrees instead. If you want your arc to be repeated across the multiple copies of the world, you can add another entry that is `[-122, 37]` to `[-221, 35]`.

Currently, the layers render your data "as is" without making assumptions on your behalf. We are considering adding special processing for the geospatial use case.
