### ISSUE TITLE
LineLayer#strokeWidth does nothing

### ISSUE THREAD

**Issue by dcposch** [uber/deck.gl#334]
Deck.gl version: 3.1.3

`LineLayer` currently implements the `strokeWidth` prop using `gl.lineWidth()`. This is apparently deprecated. WebGL lineWidth [has no effect in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=60124) or [in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=634506). In both cases, browser maintainers closed the bugs as wontfix, and are saying that:
* The minimum and maximum `lineWidth` are both 1, all lines are always 1px, and that's apparently spec compliant.
* Underlying OpenGL implementations don't necessarily support wide lines anyway.
* Apps that want wide lines should draw them using triangles.

I recommend updating `LineLayer` to draw narrow triangle strips instead of lines. This will allow lines of any width and also give Deck.gl more control over things like mitering in the future.

**Comment by dcposch** [comment]
This is especially a problem on high-DPI screens, where 1px lines can be hard to read.

**Comment by ibgreen** [comment]
> WebGL lineWidth has no effect in Chrome or in Firefox.

@dcposch Correct, `gl.lineWidth` is no longer useful except for outline/wireframe type renderings. In fact, because of this, we are dropping the `strokeWidth` props for our `GL.LINE` based layers in the upcoming release.

>  I recommend updating LineLayer to draw narrow triangle strips instead of lines. This will allow lines of any width and also give Deck.gl more control over things like mitering in the future.

We have created a new layer to handle this in our upcoming release which is being assembled on the `dev` branch (the [PathLayer](https://github.com/uber/deck.gl/tree/dev/src/layers/core/path-layer)). 

The `PathLayer` would probably work with deck.gl 3.0 (or could easily be made to work with 3.0), you could always give it a try.

**Comment by shaojingli** [comment]
@dcposch thanks for the comment. As @ibgreen mentioned above, in the upcoming deck.gl v3.1, we are doing exactly what you are suggesting.
