### ISSUE TITLE
ScreenGridLayer: Replace UBO usage with Texture2D

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#3572]
In ScreenGridLayer, max aggregated data (vec4) is provided to the shader as following :
- WebGL1 (CPUAggregation):  GridAggregator provides data as Array of 4 floats, which is used as vec4 uniform
- WebGL2 (GPUAggregation): GridAggregator provides data as `Buffer` object which is used as `Uniform Buffer Object` to provide data as uniform to the shader.

And given UBO is not supported by WebGL1 (Safari), we had to create two set of shaders in the layer.

Instead of this setup, we can do similar to what we did in HeatmapLayer, where max weight is provided to shader as a 1X1 RGBA_FLOAT_32 texture, which is sampled in vertex shader. This requires, support for float textures and Safari supports it.

NOTES: 
- This requires `OES_texture_float` extension support when using WebGL1, which has [84% support (99%  desktop browsers)](http://webglstats.com/webgl/extension/OES_texture_float)
- As per MDN this is not supported in Safari, but I verified and tested in Safari, it is supported.

**Comment by ibgreen** [comment]
Not against this, just a couple of thoughts:
- There could be a big performance difference between uniforms and texture accesses?
- In general it feels like we should be moving toward UBOs rather than away from them...
- Is it the right direction? Unless this is an overall improvement to our GPGPU approach, should we do it? How important is GPU accelerated GridLayer on Safari?

**Comment by 1chandu** [comment]
Responded to above comments in the PR.
