### ISSUE TITLE
High cpu on certain screens

### ISSUE THREAD

**Issue by Sebubu** [uber/deck.gl#3728]
#### Description
Deck raises the cpu to 70+% on certain screens. In our application the cpu even rises to 480%. One just has to initialize deck and the cpu rises.

The map works so far but lags heavily.

The issue seems to be associated with the method `setDevicePixelRatio` and the associated redraw on the canvas. The warning `luma: Device pixel ratio clamped` is logged on the console (see below).

##### Devtools performance
![](https://github.com/Sebubu/deckgl-cpu-issue/raw/master/images/devtool-performance.png)

##### Chrome task manager
![](https://github.com/Sebubu/deckgl-cpu-issue/raw/master/images/cpu-raise.png)

#### Repro Steps
- Clone the [pure-js example](https://github.com/uber/deck.gl/tree/master/examples/get-started/pure-js/mapbox) and let it run.

##### Frameworks
- deck.gl: 7.3.1
- mapbox-gl: 1.4.0

##### Browser version
- Chrome v75.0.3770.142
- Firefox 68.0

##### OS
Ubuntu 18.04.2

##### DevicePixelRatio
My device pixel ratio is 1.7000000476837158.
I have checked other devices with a ratio of 1 and the cpu didn't rise. So it probably has something to do with my ratio.

#### Logs
![](https://github.com/Sebubu/deckgl-cpu-issue/raw/master/images/console-log2.png)

**Comment by tsherif** [comment]
`setDevicePixelRatio` was also showing up in my recent profiling of deck (though not as high as reported here). I suspect checking the canvas size is causing a layout recalculation. And I'm wondering if the pixel ratio reported with all the decimal places is causing the layout to be recalculated every frame (this would be very expensive). Solution might be to always `floor` all values before checking for a resize.

Ping: @1chandu

**Comment by 1chandu** [comment]
> Solution might be to always `floor` all values before checking for a resize.

This is probably whats happening, since we are only using system provided device pixel ratio (assuming user not setting  useDevicePixels to `1.7000000476837158` @Sebubu )

Another idea was to cache clamped width and height, and once cached use these to clamp instead of running a loop. But this may not work as actual clamping seem happens based on total size, width X height. 

Here are some numbers from macbook pro , 2018 

- Max Render Buffer Size:  16384
- Max Texture Size:  16384

clientWidth: 800 , clientHeight: 600

|devicePixelRatio|drawingBufferWidth|drawingBufferHeight|WXH|
|----------------|---------------------|--------------------|------|
|100|5760|5760|33177600|
|500|5760|5760|33177600|
|25|6019|5519|33170709|
|12.5|6651|4988|33175188|
|6.25|5000|3750|1875000|

clientWidth: 800 , clientHeight: 100

|devicePixelRatio|drawingBufferWidth|drawingBufferHeight|WXH|
|----------------|---------------------|--------------------|------|
|100|7372|4500|33174000|
|500|10426|3181|33165106|
|25|14745|2250|33176250|
|12.5|10000|1250|1250000|

**Comment by Sebubu** [comment]
Wow, that merge request was fast!

@1chandu The devicePixelRatio is the natural result of a 4k display/scaling in ubuntu. The ratio has not been set manually.

**Comment by 1chandu** [comment]
@Sebubu , new deck.gl patch, 7.3.2 is published that includes the fix.

**Comment by Sebubu** [comment]
Works like a well oiled machine now 🤩
