### ISSUE TITLE
How to make layer animate itself?

### ISSUE THREAD

**Issue by efossvold** [uber/deck.gl#3795]
Is there a way of having a layer animate itself? 

I am making an app similar to [deck.gl TripsLayer example](https://github.com/uber/deck.gl/blob/7.3-release/examples/website/trips/app.js). In this example the timestamp for the TripsLayer is updated in the React component. For our app and the data we have this works fine for up to about 20k objects/trips, when the number of objects increases further it starts to strangle the CPU.

I have next to zero experience with WebGL. So my question is, is it possible to create a deck.gl layer that animates itself. I.e. in our case, extending or modifying TripsLayer to make the GPU update the timestamp, thus avoiding a "trip" to the CPU on each update.

**Comment by bbss** [comment]
I'm not a deck author and not using TripLayer yet. But AFAICT that is the way it works already, you pass the new currentTime and the gpu filters objects based on their timestamp and the trail value. It's possible something in your code invalidates your data collection that makes it run the accessors on the whole data collection again. That could make animation not-smooth. Try console.logging in your accessor, or better yet turn look into the debugging info (`deck.log.setLevel(3)` or so should do it). 

Another thing I ran into is that updating the animation got slow because the react re-render was taking too long.

**Comment by ibgreen** [comment]
We should probably write up an animation guide, but here are some thoughts in the mean time:

> So my question is, is it possible to create a deck.gl layer that animates itself. I.e. in our case, extending or modifying TripsLayer to make the GPU update the timestamp, thus avoiding a "trip" to the CPU on each update.

Yes absolutely! As you say, the most efficient animation is done on the GPU. The trick is to not update anything in the layer on the CPU (JavaScript) side but just change a time uniform in the layer shader (GLSL) and redraw every frame.

- The `TripsLayer` takes a prop `currentTime` which does require a React update Deck maintains a set of `animationProps` on `Layer.context.animationProps`. These animation "props" change every frame and include `time`, and they are updated independently of React. Using these instead of `props.currentTime` would keep the animation updating without React updates. .

>  For our app and the data we have this works fine for up to about 20k objects/trips, when the number of objects increases further it starts to strangle the CPU.

> Another thing I ran into is that updating the animation got slow because the react re-render was taking too long

Since your perf depends on the number of objects, your app is most likely triggering updates of attributes on every render. Techniques discussed below (such as no longer updating the timestamp every frame in React) is not going to help with that. If you can't see what is causing deck to update every frame, you could try activating logging (e.g. set `deck.log.priority = 2` in the browser console).

Hope this gives some initial clues

**Comment by efossvold** [comment]
Thank you for your reply.

> Deck maintains a set of animationProps on Layer.context.animationProps

Is there any documentation on animationProps? Can't find anything in the doc about it.

You are mentioning both `Layer.context.animationProps` as well as the time uniform in the layer shader. Not sure whether you mean updating the animationProps in layer, the time uniform in the shader or both. Is there an example somewhere?

> Since your perf depends on the number of objects, your app is most likely triggering updates of attributes on every render.

This is not the case. We're using useRef  to get the same object ref for the data on every render. However, using logging as you recommended I realized that the number of objects is actually way higher than I initially thought. Since every trip has 60 data points the number of objects is actually 1.2M (20K*60).

**Comment by ibgreen** [comment]
> Is there any documentation on animationProps? Can't find anything in the doc about it.

No, `animationProps` are not documented in deck.gl. There is however some documentation in luma.gl: https://luma.gl/docs/api-reference/core/animation-loop#callback-parameters

Note that you absolutely do not need to use animationProps, they are just a convenience, you can feed in your own time uniform values.

> Not sure whether you mean updating the animationProps in layer, the time uniform in the shader or both.

The key is updating the shaders to render animation based on a uniform, and then updating the javascript to pass in that uniform every frame.

> Is there an example somewhere?

There is no example that does everything you need. The trips layer does use the important concepts, feeding in a time uniform to the shaders:

- https://github.com/uber/deck.gl/blob/7.3-release/modules/geo-layers/src/trips-layer/trips-layer.js#L61
- https://github.com/uber/deck.gl/blob/7.3-release/modules/geo-layers/src/trips-layer/trips-layer.js#L91

Since this is not directly documented and we don't have an example that does everything, this will most likely require a bit for "poking around" on your part. It is hard to give you an expectation of how much work this would be for you, but it may give you some confidence that for someone who is comfortable with webgl programming this should be quite straightforward (as long as the animation effect you want to achieve can be implemented in the shader using a uniform).

> Since every trip has 60 data points the number of objects is actually 1.2M (20K*60).

OK. We usually still see good performance up to about a few million vertices, so if it is noticeably slow I would still be a bit suspicious that you are triggering some CPU side update. Maybe do a quick profile in Chrome to see if you can glean where time is spent?

**Comment by efossvold** [comment]
Thanks for your help! I managed to do the computation of the timestamps on the GPU, so now there's no re-rendering over the parent (react) component, everything is happening in the custom TripsLayer. I had to set _animation to true on the DeckGL component, that is correct isn't to get Deck to run the animation continuously by itself?

> OK. We usually still see good performance up to about a few million vertices, so if it is noticeably slow I would still be a bit suspicious that you are triggering some CPU side update. Maybe do a quick profile in Chrome to see if you can glean where time is spent?

Performance is better, though still not at the expected and desired level. With 3M instances framerate is only running at 10 per seconds on a Macbook with Radeon Pro 450. Doing a profile in chrome shows that "Animation Frame Fired" takes around 100ms, all other calls takes only around 1-2ms.

**Comment by ibgreen** [comment]
> With 3M instances framerate is only running at 10 per seconds on a Macbook with Radeon Pro 450

Without actually seeing your code it is hard to say if there are any obvious improvements that can be done. 
- One thing worth noting that "fill rate" can be a big issue, If you are drawing/overdrawing a lot of pixels, and e.g. 4K displays can really lower perf. 
- Try setting the deck `useDevicePixels: false` prop to eliminate fill rate as the cause.

@tsherif @1chandu

**Comment by ibgreen** [comment]
> . I had to set _animation to true on the DeckGL component, that is correct isn't to get Deck to run the animation continuously by itself?

Yes, that is why we added this prop, you can use this approach for now.

**Comment by ibgreen** [comment]
https://deck.gl/#/documentation/deckgl-api-reference/deck?section=usedevicepixels-boolean-number-optional-

**Comment by efossvold** [comment]
> Try setting the deck useDevicePixels: false prop to eliminate fill rate as the cause.

This increased the frame rate with about 2 per second.

> Without actually seeing your code it is hard to say if there are any obvious improvements that can be done.

That's understandable. It is a corporate project, so unfortunately I'm not able to share the code here.
