### ISSUE TITLE
IconLayer render tests randomly failing

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#4039]
CI randomly fails on the IconLayer auto-packing render tests. This is likely due to the icons not yet loaded when the screen is captured.

To fix this we will need a way to determine if the `IconManager` has done loading. Each test case can optionally define their own ending criteria, see [onAfterRender](https://github.com/uber/deck.gl/blob/master/docs/api-reference/test-utils/snapshot-test-runner.md#addtestcase-arrayobject):

```js
{
  name: 'icon-layer-auto',
  viewState: {...},
  layers: [...],
  onAfterRender: ({layers, done}) => {
    if (layers[0].state.iconManager.loaded) {
      // data is loaded
      done();
    }
  },
  goldenImage: '...'
}
```

**Comment by ibgreen** [comment]
For the long term, maybe we should create and RFC a generic loading tracking mechanism into each layer, so that the layer can maintain a flag and there can e.g. be an `onAllLayersLoaded` callback on deck.gl that fires after each setProps call? 

Not only for tests, but also for video generation this becomes important, as the video generator ideally should wait for all assets to be loaded before rendering next frame, a use case we have been looking at recently.

**Comment by Pessimistress** [comment]
#4091
