### ISSUE TITLE
Hexagons in hexagon layer resize when viewport is moved

### ISSUE THREAD

**Issue by vallendm** [uber/deck.gl#4051]
Hello, 

I've been looking at deck.gl for inclusion into a mapping project we are working upon which is based on Mapbox. So far I'm very impressed - deck.gl looks excellent. 

One thing that we've been looking to add for a while is a hexbin layer to our maps. I've been trying the Hexagon layer and it look great at city level and below but I noticed something on a global level when viewing a dataset containing techtonic plates/volcano locations. 

If I plot the volcano location I can get a view something akin to this 

![image](https://user-images.githubusercontent.com/7239758/71161006-7dad9280-2240-11ea-91db-959c6d6d684c.png)

However if I then try to move to a different view - look closer at Iceland say - the hexagon start to overlap eachother.

![image](https://user-images.githubusercontent.com/7239758/71161142-b6e60280-2240-11ea-8dd0-ba87a2fb2ae3.png)

This is only corrected if I remove the layer and re-add it at the new view location. Is this expected? Is it possible to recalculate the hexagons after a zoom/translate operation or force them to be recalculated without having to remove the layer.

**Comment by Pessimistress** [comment]
@heshan0131

**Comment by wlfei0502** [comment]
I have the same problem

**Comment by Pessimistress** [comment]
@heshan0131 In the HexagonLayer, aggregation is done in in common space (the mercator plane). There are currently two issues regarding how the layers handle the conversion between world units (user-provided radius) and common units (aggregation radius):

- When a new aggregation is triggered, user-provided radius is converted from meters to common units at the *current* viewport latitude. This makes the aggregation result dependent on a transient state of the application instead of the source data. A more sensible approach would be using the first data point, or the center of the bounding box.
- Once aggregation is done, `radius` and `angle` must be updated when the viewport moves.

**Comment by 1chandu** [comment]
> using the first data point, or the center of the bounding box

GridLayer uses, bounding box.

**Comment by Pessimistress** [comment]
This is fixed in 8.0.11.
