### ISSUE TITLE
`longitude` must be supplied assertion when using transitionDuration auto.

### ISSUE THREAD

**Issue by cosullivan** [uber/deck.gl#4077]
#### Description
I am trying to update the initial view of the map once it has loaded to apply a pitch and a bearing. When using 

```
transitionDuration: "auto"
```

I receive an _Error: `longitude` must be supplied_ in the MapController, but when using a numeric value (ie, 2000) then the transition works as expected.

I have a sample here;
https://codesandbox.io/s/sleepy-lamport-yhx09

Thanks.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.1

**Comment by Pessimistress** [comment]
You should only add transition options when the view state changes, aka when the buttons are clicked. Overwriting the transition props in the view state makes the controller unusable (triggers a transition every time you pan the map, for example).

The error is because when the component initially load, there is no view state to transition *from*. With that said, crashing the app seems unnecessary. @1chandu

**Comment by Pessimistress** [comment]
The crash is fixed in 7.3.12/8.0.2
