### ISSUE TITLE
v4: Support colorRange and colorDomain in ScreenGridLayer

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#429]
Essentially align `ScreenGridLayer`'s aggregation functionality with `GridLayer` and `HexagonLayer`.

Proposed changes:
- deprecate prop: `minColor`
- deprecate prop: `maxColor`
- add prop: `colorRange` (replaces the former min and max color)
- add prop: `colorDomain` (optional, default to actual range of count)
- change linear interpolation to using `d3.quantizeScale`

TODO:
 - [X] Add label and assign to milestone 
 - [X] Coding
 - [x] Doc update
 - [x] Whats new update 
 - [x] Update rendering test

Per discussion with @ibgreen and @shaojingli, we could consider pushing this change when we upgrade to GPU-based aggregation in 4.1.

**Comment by gnavvy** [comment]
If we were to do this in 4.1, we might also want to add an opacity dimension to the color mapping. It would be helpful for cases where we only want to highlight certain value ranges and set others to translucent.

Below is an example, the second panel on the left: the x-axis is a color domain, and y-axis the corresponding opacities; users can easily fine tune the visibility by brushing the transfer function editor.

<img width="600" alt="screen_shot_2017-03-15_at_9_39_40_pm" src="https://cloud.githubusercontent.com/assets/144743/23982254/789904c4-09c9-11e7-8044-78fc81d991e3.png">

Should be useful for our point-cloud and aggregation layers.

**Comment by ibgreen** [comment]
> Essentially align ScreenGridLayer's aggregation functionality with GridLayer and HexagonLayer.

> deprecate prop: minColor
> deprecate prop: maxColor
> add prop: colorRange (replaces the former min and max color)
> add prop: colorDomain (optional, default to actual range of count)

Agreed. We missed this in the API audit, this should really have been part of 4.0. 

> change linear interpolation to using d3.quantizeScale

I like the direction in terms of color scales, just a heads up: my instinct is to push back on any proposal that requires pulling in new non-optional dependencies. I'd feel more comfortable if we came at this with the idea of making it easy for the application to use things like `d3.quantizeScale` with our layers. E.g. it should be the app that would install and import this module, and then the app would pass the module (or some object generated from it, like a `scale`) to deck.gl, rather than the `ScreenGridLayer` importing ` d3.quantizeScale` directly.

For these reasons, I'd prefer to see this bullet as a separate PR.

> If we were to do this in 4.1, we might also consider adding an opacity dimension to the color mapping.

This is a very cool idea. It feels like we have enough ideas to enable us to have a good think about color ranges and what features we want to support across layers (d3 color scale compatibility, various types of color breaks, advanced features like this etc), come up with a plan, and make "improved color scale support" a key feature of the next release.

As a slightly more speculative idea we might also be able to create a shader module that does smart things with color scales (they could be rendered into textures for super quick lookup etc).

**Comment by shaojingli** [comment]
It should have made the 4.0 but never mind we could make it part of the effort we planned to unify all our aggregating layers.

**Comment by 1chandu** [comment]
Re-open, accidental close.

**Comment by 1chandu** [comment]
Resolved in #1522
