### ISSUE TITLE
Lighting doesn't work as expected after the model matrix is enabled

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#440]
The light seems to be moving affected by the the model matrix, which it shouldn't

**Comment by shaojingli** [comment]
Currently, the clip space position of the geometry is calculated in two stages
``` vec4 position_worldspace = vec4(project_position(instancePositions), 1.0);```
```gl_Position = project_to_clipspace(position_worldspace) + vec4(vertex, 0.0, 0.0);```

The modelMatrix is applied in the second stage in project_to_clipspace() function, which should have been implemented in the first stage.

**Comment by ibgreen** [comment]
> The modelMatrix is applied in the second stage in project_to_clipspace() function, which should have been implemented in the first stage.

Yes looks like we can implement this fix without an API change to the `project` shader module which is nice. 

Just an idea: If we want to separate the matrix multiplications, we need to expose the model matrix as a uniform (`project_uModelMatrix`?) which is fine of course.  But since we don't always have a `modelMatrix` it could be worth adding a second boolean uniform (`project_uHasModelMatrix`?) to indicate whether the modelMatrix is present, and only do the multiplication when it is provided (rather than always multiplying with an identity matrix).

**Comment by shaojingli** [comment]
This might have been fixed by https://github.com/uber/deck.gl/pull/805

Need verification

**Comment by ibgreen** [comment]
Closing, I believe this is fixed. Reopen if not.
