### ISSUE TITLE
Change default depth test state to true, update default blending mode

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#491]
I noticed that all our examples and demos set depth test to true and depth function to LEEQUAL in its onWebGLInitialized() call back. Asking the ***app*** to handle WebGL states are makes me very uncomfortable.  Doing it directly through WebGL APIs is even worse. 

Should deck.gl or the layers handle this? What's the use case for disabling depth case?

@Pessimistress @ibgreen @gnavvy

**Comment by ibgreen** [comment]
This is just my brain dump as background to the discussion. 

> What's the use case for disabling depth case?

Disabling depth test can be useful when the app is only rendering flat layers, or even when rending all flat layers + a single extruded layer. The reason is that disabling depth test completely circumvents z-fighting issues and allows the app to reason about drawing order just as it would in a traditional application.

What we could be very reasonably to discuss is what the default depth test setting should be. If almost all deck.gl apps have to use webgl calls to turn on depth test, then maybe that should be the default so that only apps that don't want it have to define `onWebGLInitialized`. We could make that change now and doc it as a breaking change in our upgrade guide.

> Asking the app to handle WebGL states makes me very uncomfortable. Doing it directly through WebGL APIs is even worse.

* For good or bad, the design of deck.gl has been to provide direct access to gl context and provide luma.gl as an optional wrapper for apps that don't want to deal with the raw api. 
* In addition, luma.gl was not intended to be a "thick" wrapper to encapsulate every single GL call. Why encapuslate simple calls like `gl.clear` etc. Only encapsulate where the raw API is cumbersome.
* That said, GL state management is an area that we DO want to provide support for in luma.gl and a lot of work has been done on it. Unfortunately the luma.gl state management feature wasn't quite ready in time for luma3.0/deck4.0 but we could absolutely have it ready for say a deck.gl 4.1 in a month or two. I can present to the proposed API separately.

**Comment by shaojingli** [comment]
> Disabling depth test can be useful when the app is only rendering flat layers, or even when rending all flat layers + a single extruded layer. The reason is that disabling depth test completely circumvents z-fighting issues and allows the app to reason about drawing order just as it would in a traditional application.

This sounds reasonable for me for now. But eventually, we probably will solve the z fighting by having a better rendering controller in our LayerManager.

> For good or bad, the design of deck.gl has been to provide direct access to gl context and provide luma.gl as an optional wrapper for apps that don't want to deal with the raw api.

What I'd like to discuss here is whether the **deck.gl user** should know how to use WebGL or users on this level should only be exposed to some higher level concepts. For example, it's reasonable that a **deck.gl user** want to enable/disable depth test, but requiring them to know to use these two specific WebGL calls seems to be too much for me.

The situation is different with the layer developers. If a developer wants to create new layers, he must know some WebGL APIs. This is required by our current model of abstraction.

> In addition, luma.gl was not intended to be a "thick" wrapper to encapsulate every single GL call. Why encapuslate simple calls like gl.clear etc. Only encapsulate where the raw API is cumbersome.

I didn't mean encapsulating all calls. This is definitely NOT what we'd like to do. 

> That said, GL state management is an area that we DO want to provide support for in luma.gl and a lot of work has been done on it. Unfortunately the luma.gl state management feature wasn't quite ready in time for luma3.0/deck4.0 but we could absolutely have it ready for say a deck.gl 4.1 in a month or two. I can present to the proposed API separately.

Yeah, this is a separate task that can eventually solve everything once and for all. 

I guess I should raise the issue but any changes should go after v4.0 as the release date is too close given other higher priority issues with have.

**Comment by ibgreen** [comment]
Now that we have support for polygonOffsets to help combat z-fighting I feel much better about enabling depth test by default. Let's do it for our next major release! Also blending mode should be updated.

**Comment by 1chandu** [comment]
This is already done in  deck-js.js `_onRendererInitialized`.
