### ISSUE TITLE
Further documentation needed

### ISSUE THREAD

**Issue by mhoangvslev** [uber/deck.gl#592]
I'd like to see more explicit and perhaps more complete documentation:
- How to start section (how to create scene, add camera, mesh, material, etc.)
- Something like Javadoc for every element of the code.

I am looking for something like three.js

**Comment by ibgreen** [comment]
@mhoangslev 

This is great feedback - we are very interested in improving the docs. 

That said, we already have
* a [getting started section](https://uber.github.io/deck.gl/#/documentation/getting-started/installation)
* detailed [API reference](https://uber.github.io/deck.gl/#/documentation/api-reference/attribute-manager)
* interactive [layer documentation](https://uber.github.io/deck.gl/#/documentation/layer-catalog/arc-layer)

> (how to create scene, add camera, mesh, material, etc.)

Note that deck.gl does not have a scenegraph system like THREE.js, and also deck.gl does not have mesh and material concepts. Each layer's shaders determine how that layer is rendered.

Instead, you compose your visuals using deck.gl `layers`, instead of using `THREE.Mesh`:es, so your "scene" is the list of layers you pass in.

Cameras correspond pretty closely to 'Viewports` in deck.gl . Often the app doesn't have to create viewports (deck.gl coordinates with the mapbox map and automatically generates a synchronized viewport). There are examples like the `examples/plot` that shows how to create custom viewports. This is an area we are improving for the next release.

I'm now thinking that a section in the docs explaining deck.gl to programmers coming from a THREE.js background could be good approach?

**Comment by shaojingli** [comment]
Thanks @ibgreen for replying.

> I'm now thinking that a section in the docs explaining deck.gl to programmers coming from a THREE.js background could be good approach?

This is a good idea. But we probably need to emphasize there that deck.gl is not really on the same abstraction level as THREE.js. luma.gl is more of that.

**Comment by mhoangvslev** [comment]
Thanks @ibgreen for your reply.

Now I understand more about how deck.gl works.
It would be really nice if you can centralize all documentations in one place: luma.gl documents will be mixed with deck.gl documents and a filter to improve searching experience would be nice.

**Comment by ibgreen** [comment]
> It would be really nice if you can centralize all documentations in one place: luma.gl documents will be mixed with deck.gl documents and a filter to improve searching experience would be nice.

Thanks for your feedback, much appreciated, and agreed! 

These changes will take some work though, so I have added requests for doc search and better integration with luma.gl docs to our v4 feedback tracker task - it will have more visibility there as we use that tracker to plan for coming releases.

Closing this for now.

**Comment by mootari** [comment]
> I'm now thinking that a section in the docs explaining deck.gl to programmers coming from a THREE.js background could be good approach?

That is an excellent idea. I imagine that even a high level overview of how three.js concepts translate to deck.gl (or not) would be a great starting point.
