### ISSUE TITLE
ScreenGrid layer affects rendering of other layers in layer browser

### ISSUE THREAD

**Issue by ericsoco** [uber/deck.gl#602]
A number of layers render incorrectly when the ScreenGridLayer is turned on in the layer browser:

![HexagonCellLayer + ScreenGridLayer](https://cloud.githubusercontent.com/assets/1127259/25498126/bdd29df0-2b3b-11e7-8220-733a912054a0.png)

![PointCloudLayer + ScreenGridLayer](https://cloud.githubusercontent.com/assets/1127259/25498127/bf72c02c-2b3b-11e7-9386-33692ae4e068.png)

Not sure if this is a regression or a long-standing never-before-noticed bug.

**Comment by ericsoco** [comment]
Or...is this intended behavior? If so, we should update [the docs](https://github.com/uber/deck.gl/blob/master/docs/layers/screen-grid-layer.md) to indicate this is what is meant by _Screen_Grid.

**Comment by shaojingli** [comment]
No.. this is not intended but it's been there for quite some time. Thanks for creating the issue to track it.

**Comment by ibgreen** [comment]
Looks like z-buffer pollution?

**Comment by 1chandu** [comment]
The problem here is depth test and order of rendering. ScreenGrid layer renders in screen space with z value of 0.0 which happens to be occluding other layers. Layers that are rendered before (any layer that is listed above ScreenGrid in UI) are fine as they get blended with ScreenGridLayer, but all other layers rendered after (layers listed below ScreenGrid) seems to be get occluded. Couple of options to fix :

1. Disable depth writes in ScreenGrid layer.
2. Re-order the layers in layer-browser example, so that ScreenGrid is rendered last.

I prefer 2, as this problem occurs only when multiple layers are rendered and 2 only changes the example.

CC: @ibgreen @shaojingli @Pessimistress

**Comment by ibgreen** [comment]
> 1. Disable depth writes in ScreenGrid layer.
> 2. Re-order the layers in layer-browser example, so that ScreenGrid is rendered last.

Isn't there an option 3 - disable depth writes not in the `ScreenGridLayer` itself but in the application (layer-browser) by adding:
```
   parameters: {
      depthMask: false
   }
```
to the props when rendering the layer. 

This would have the added benefit of providing a test case for our new `parameters` prop.

> I prefer 2, as this problem occurs only when multiple layers are rendered and 2 only changes the example.

FWIW, I always imagined a `ScreenSpace` named layer would be special in this sense. But perhaps there are complications with doing that. I don't have a strong sense for what the right trade-off is. For now maybe use option 3?
