### ISSUE TITLE
create-react-app: Identifier 'Buffer' has already been declared

### ISSUE THREAD

**Issue by espiegel** [uber/deck.gl#624]
When I create a new react app using "create-react-app" and using the deck.gl example shown here:  https://uber.github.io/deck.gl/#/documentation/getting-started/using-with-react

I get the following error:
```
bootstrap c8f9d56…:555 Uncaught SyntaxError: Identifier 'Buffer' has already been declared
    at __webpack_require__ (bootstrap c8f9d56…:555)
    at fn (bootstrap c8f9d56…:86)
    at Object.<anonymous> (buffer_group.js:4)
    at __webpack_require__ (bootstrap c8f9d56…:555)
    at fn (bootstrap c8f9d56…:86)
    at Object.<anonymous> (bucket.js:4)
    at __webpack_require__ (bootstrap c8f9d56…:555)
    at fn (bootstrap c8f9d56…:86)
    at Object.<anonymous> (circle_bucket.js:3)
    at __webpack_require__ (bootstrap c8f9d56…:555)
```

**Comment by ibgreen** [comment]
Maybe if you could open a PR adding a minimal example using `create-react-app` to the deck.gl examples folder? We could try to see if we can get it working there.

PS - there is a related discussion in react-map-gl repository, but no solutions yet.

**Comment by espiegel** [comment]
Thanks @ibgreen , I created the PR here: https://github.com/uber/deck.gl/pull/626

**Comment by ibgreen** [comment]
Thanks for putting up the PR. 

I tested it locally. As suspected, the problem is indeed related to mapbox-gl and the fact that webpack [needs a webpack alias](https://mikewilliamson.wordpress.com/2016/02/24/using-mapbox-gl-and-webpack-together/) to bring in their precompiled dist. 

I went into node_modules and edited the webpack config in `create-react-apps`'s `react-scripts` https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L94 and added the line 
```
      'mapbox-gl$': pth.resolve('./node_modules/mapbox-gl/dist/mapbox-gl.js')
```
and things worked beautifully again.

Unfortunately `create-react-app` prevent you from accessing the webpack config (easy to verify [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/scripts/start.js#L38)),  I don't see anything we can do from `deck.gl` or `react-map-gl` here. 

Two options come to mind:

* Since the maintainers of `create-react-app` intentionally (see comments in issues on their repo) prevent you from accessing the webpack config, you could alway open a PR towards them and ask if they can add this alias to their permanent config?

* And you could of course join the ranks who are petitioning mapbox-gl for simpler webpack support (see issues on their repo).

**Comment by stereobooster** [comment]
Related: https://github.com/uber/react-map-gl/issues/176

> Since the maintainers of create-react-app intentionally (see comments in issues on their repo) prevent you from accessing the webpack config, you could alway open a PR towards them and ask if they can add this alias to their permanent config?

This is not an option. In this case they will suggest to use `eject` command.

Proper solution is to ask for ES6 modules in mapbox-gl. See https://github.com/mapbox/mapbox-gl-js/issues/4664
