### ISSUE TITLE
master branch fails browser test

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#661]
`npm run test-browser` returns 

<img width="938" alt="screen shot 2017-05-24 at 10 46 22 am" src="https://cloud.githubusercontent.com/assets/21322704/26417543/5948f224-406e-11e7-82c2-3e53dad35e15.png">

**Comment by ericsoco** [comment]
Another test suite? TIL. We need a way to wrangle all these test suites. See @ibgreen's [comment](https://github.com/uber/deck.gl/issues/659#issuecomment-303757912) for more context.

**Comment by ibgreen** [comment]
> Another test suite? TIL. We need a way to wrangle all these test suites.

OK - some background

It's the same test suite, but run in the browser. 

While it would be awesome to have CI do both node *and* browser testing, I haven't found a reliable way to run it on Travis, so it doesn't get executed by the main test script.

But since I find debugging in the browser much easier than debugging in node, I try to keep the script in good working order.

But since it is not automatically run, it doesn't get tested before every check-in, so it does occasionally degrade on master.

We did have a partially working integration with electron (headless browser environment) and testron, but it was flaky. If we could get something like that solid (perhaps Chrome headless mode), it would be good to add it to the main set of tests.

**Comment by ibgreen** [comment]
Dup of #675
