### ISSUE TITLE
Run point-cloud-ply/point-cloud-laz example in local

### ISSUE THREAD

**Issue by jtewari08** [uber/deck.gl#743]
Hi,
I am trying to run point-cloud-ply/point-cloud-laz example locally but i am not able to do it.
I don't see any README.md.
Please help me in this.

Thanks

**Comment by ibgreen** [comment]
@gnavvy

**Comment by jtewari08** [comment]
Hi,
We want to use this layer for one of or product and in middle of a POC. It would be very nice if we can get a response.
Thanks

**Comment by gnavvy** [comment]
@jtewari08 sorry for the late reply. Could you provide more details what did not work, please?

The examples are sharing the same flow to use as described here:
https://github.com/uber/deck.gl/tree/master/examples

**Comment by jtewari08** [comment]
Hi,

The issue is when i am trying to add my own .ply file i am getting this
error. What can we the possible reason for this error?

**Comment by gnavvy** [comment]
> The issue is when i am trying to add my own .ply file i am getting **this error**. What can we the possible reason for this error?

Could you provide more information regarding "this error"?

My guess is the property definition of the .ply file. 

You can try open your ply file with a text editor, and check the first few lines. Here is an example: https://courses.cs.washington.edu/courses/cse558/01sp/software/scanalyze/points.html

Since there is no standard way of defining the property names, we only added in the point-cloud-example the common property names we found from online .ply files. If there's a mismatch between the names, you will have to make changes to the code accordingly so the positions of the point can be properly extracted and nomalized.
