### ISSUE TITLE
Layer to use to show a string on map

### ISSUE THREAD

**Issue by Nedo93** [uber/deck.gl#751]
Hi guys as a simple question, what layer is better to use to show a simple string on the map? 
Considering that I will put that string-level on the top of a scatterplot layer to represent someone moving on the map.

Thank you in advance if you can answer this question.

**Comment by rivulet-zhang** [comment]
Hi @Nedo93 `examples/sample-layers/label-layer` may be something of your interest. A variant of `label-layer` is `examples/tagmap` that provides an occlusion-free label layout by moving the labels a bit from their original positions. If you just have a few strings to show and do not care about the overlap, `label-layer` is definitely a good choice. Otherwise, tagmap could be an option that shows a high-level summary of a relatively large number of labels.

**Comment by Nedo93** [comment]
Thank you very much, this seems exactly what we were looking for :)
