### ISSUE TITLE
`useDevicePixelRatio`: Address all cases for retina displays

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#843]
#865 added a new prop `useDevicePixelRatio` to DeckGL component, which will be passed to `AnimationLoop` and `LayerManager` (for picking/querying).

Remaining: We are still using `window.devicePixelRatio` in following places:
 - [x] wheel-input.js
 - [x] layer:screenToDevicePixels()
 - [x] examples
Make sure above usages are in sync with DeckGL prop.

**Comment by ibgreen** [comment]
Adding comments from discussion in PR #850

> Is it necessary to draw the picking buffer in high DPI? Mouse coordinates are always in screen pixels.

So what we are discussing now is to make it easy for the app to select whether to draw in High-DPI or not (since it has a significant perf impact), and maybe even add a checkbox to the examples enabling the user to try with and without.

I would expect that to be a new prop on the `DeckGL` (`useHighDPI`, `useDevicePixelRation`, `useRetina` or similar) and it would affect both normal render and picking.

Once that is done, a second reasonable question is whether we could use different values for picking and main rendering. For pixel perfect picking an app might want them to be the same, but many apps want to use a picking radius for better fat finger sensitivity and then it might not matter anyway.

**Comment by Pessimistress** [comment]
> many apps want to use a picking radius for better fat finger sensitivity and then it might not matter anyway.

Speaking of pickingRadius, it already has a significant hit on perf as we process `R^2` pixels. With retina display that goes up to `4R^2`.

**Comment by 1chandu** [comment]
#865 added a new prop to DeckGL component, which will be passed to `WebGLRenderer` and `LayerManager` (for picking/querying).
Remaining:
We are still using `window.devicePixelRatio` in following places:
 - wheel-input.js
 - layer:screenToDevicePixels()
 - examples
Make sure above usages are in sync with DeckGL prop.

**Comment by ibgreen** [comment]
I think layer:screenToDevicePixels can be deprecated now. It was used briefly for GL.LINES but that is not supported any more. and now we have a uniform instead.

**Comment by shaojingli** [comment]
Bump this to P1

**Comment by 1chandu** [comment]
Resolved by #1006.
