### ISSUE TITLE
Intel graphics card offset issue

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#86]
This issue only appears on Intel graphics card.

To reproduce:
1. Using an Intel only (e.g. Macbook Pro 13'') laptop, or use [gfxCardStatus](https://gfx.io/) to disable the discrete AMD/nVidia Graphics card.
2. Remove other layers and only focus on the choropleth layer (this bug is likely to affect all layers but it is easier to bug on the choropleth layer with an underlying map for reference)
3. Zoom into street level and check the choropleth contours, there is positive offset in y direction.
<img width="1218" alt="screen shot 2016-09-27 at 1 42 22 pm" src="https://cloud.githubusercontent.com/assets/144743/18895139/1b0ea462-84cc-11e6-9728-1913464cc1eb.png">

Possible causes:
1. Since this only happens on Intel cards, the code logic should be correct;
2. We only observe the offset in the y direction, and the offset scales proportionally as we zoom in and out, so very likely this is related to the mercator projection, in which the calcualtion for latitude invovles non-linear transformations (tan/log); where the calculation for the longitute (linear) does not suffer from this. And there might be precision issues/bugs in the Intel Math library (thanks @shaojingli for the hints).
3. highp mediump related? maybe?

**Comment by shaojingli** [comment]
I can verify that the inaccurate tan() function from Intel's GLSL compiler is the root cause of this issue. I created a "intel_workaround" branch and replaced the tan() with my newly implemented tan_fp64(). The issue was no longer there. Please help me verify.

Of course, using an fp64 function seems to be an over-kill for this. We only need to have a more accurate tan() function in single precision.

**Comment by ibgreen** [comment]
@gnavvy Fix published in v3.0.0-beta17. Please reopen if not working.
