### ISSUE TITLE
fp64 prop is not explicitly mentioned in the Scatterplot layer doc

### ISSUE THREAD

**Issue by brianc** [uber/deck.gl#906]
Howdy - thanks for the awesome library!  I am using the scatterplot and whenever I zoom the dot 'jiggles' around.  I tried to fiddle with the various settings on the map & the layer but to no avail.  I am guessing its re-computing the layout every time the viewport changes and maybe there's some floating point math that's not precise enough or something?

![dot](https://user-images.githubusercontent.com/50081/30037738-63d925c2-9183-11e7-8ee8-f2939728cb52.gif)

In the above animated gif the *only* thing I am doing (which is unfortunately non-obvious in the picture) is mouse-wheel zooming out slowly. Every time the mouse wheel 'ticks' and changes the zoom level the dot jiggles and changes shape. 

This behavior is very obvious when you're zoomed close in, but is also present at farther out zoom levels.

It's also reproducible on [this example](http://uber.github.io/deck.gl/#/documentation/layer-catalog/scatterplot-layer) from the docs if you choose one of those circles and zoom way in.  Eventually it'll start jiggling around as well.

![dot](https://user-images.githubusercontent.com/50081/30037780-da869e0c-9183-11e7-94dd-61b8a1be45ea.gif)

Any recommendation for a way to fix this?

**Comment by 1chandu** [comment]
@brianc , this is due to 32 bit floating point precision not being enough, you need to enable `fp64` prop to avoid  this.

More details in documentation : https://uber.github.io/deck.gl/#/documentation/advanced-topics/64-layers

**Comment by brianc** [comment]
@1chandu thank you for your response! I actually stumbled across that myself in the documentation *right now* and came back to update & close the issue.  I really appreciate the fast response ❤️ .  It might be worth-while to call that out in a bit more detail, but either way I'm fixed now & the lib is awesome. 💃

**Comment by ibgreen** [comment]
@1chandu 

I took a look at the docs and it seems that this is (at least partly) a documentation issue that should be easy to address:

The docs for some layers that support 64-bit mode, like [`ArcLayer`](https://uber.github.io/deck.gl/#/documentation/layer-catalog/arc-layer), mention the `fp64` prop, but [`ScatterplotLayer`](https://uber.github.io/deck.gl/#/documentation/layer-catalog/scatterplot-layer) does not. 

I think we should be consistent, and since not every layer supports `fp64`, we should probably just mention it in each supporting layer.

Also I believe that this has been brought up before by @nrabinowitz
