### ISSUE TITLE
Picking and highlighting broken on master

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#979]
- When mouse point moved away from a selectable object to no object area, 'onHover' message on `layer-browser` isn't cleared out.
- Auto highlighting is not working.

**Comment by ibgreen** [comment]
I just noticed an issue on line https://github.com/uber/deck.gl/blob/master/src/core/lib/draw-layers.js#L200

Reusing parameters here brings in previous layers parameters. We must use a fresh variable each iteration. This was a bug I introduced in my split of draw and pick into two files.

Not sure if your bug is related.

**Comment by 1chandu** [comment]
Turns out picking and highlighting are two different problems introduced with picking refactor, preparing a PR.

**Comment by 1chandu** [comment]
Resolved in #982
