### ISSUE TITLE
Combining several Examples into one Application

### ISSUE THREAD

**Issue by dleitner100** [uber/deck.gl#983]
Let's say I would like to display three deck.gl examples in one application (e.g. having a landing page with 3 buttons to start the example).
From the documentation it says that you need to install npm for each example. Is there another way?
Thanks.

**Comment by ibgreen** [comment]
> From the documentation it says that you need to install npm for each example. Is there another way?

@dleitner100 Do you want to build an app that combines our examples or do you just want to link to the examples on our web page?

Assuming the first, our examples are designed to be stand alone so that you can copy each directory out and install and build it independently of the deck.gl repo.

If you'd like to combine examples you'd be expected to cut and paste code together. There are typically two pieces you need to copy from each example, the data loading code and layer rendering code.
