### ISSUE TITLE
Class name cleanup

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#987]
Clean up names in deck.gl so that file names / class names / export, import names are consistent.

**Comment by ibgreen** [comment]
We are generally pretty consistent. Any particular files that stick out as needing attention?

**Comment by shaojingli** [comment]
For example, in `src/core/controllers/`, we are actually defining various `Controls` classes, `MapState` and `OrbitState` classes. We need to rename either the folder or the classes

The class defined in `ViewportController.js` is `Controller`

**Comment by ibgreen** [comment]
Yes, I see what you mean. 
* From a previous discussion, since `controls` refers to things like buttons etc, we wanted to avoid that word and call these something else (like controllers). 
* And since the naming was still up in the air and changing, it was hard to be rigorous.

My RFC contains one attempt to settle on names, something like:
* `ViewState` (collects all position fields from MapState, OrbitState, FirstPersonState).
* `Controller` -> base class for `MapController`, `ThirdPersonController`, `FirstPersonController` (collects all `ViewState` update logic from MapState, OrbitState, FirstPersonState). They all generate a stream of `ViewState`s.
* `Viewport` -> base class for `MapViewport`, `ThirdPersonViewport`, `FirstPersonViewport` - they all consume `ViewState`s and display them in different ways.

The master component could either be `DeckGL` or a `ViewStateController`.

**Comment by Pessimistress** [comment]
@ibgreen Can we also rename the `Controls` class to something else? `Controls` vs. `Controller` is extremely confusing even in our internal discussions.

**Comment by jianhuang01** [comment]
#990
